import type { EventCardDef } from '../../types';

/** Bank deck. Slow, regulated, and profitable beyond reason. */

export const BANK_CARDS: EventCardDef[] = [
  {
    id: 'bank_loan',
    category: 'bank',
    title: 'Large Commercial Loan Request',
    body: 'A developer wants a nine-figure facility. The collateral is a project that does not exist yet and the relationship is worth a fortune.',
    choices: [
      {
        label: 'Approve it',
        hint: 'Large fees, real risk',
        odds: 0.65,
        good: { text: 'The project completes on time. Origination fees and a client for life.', cashSeconds: 340 },
        bad: {
          text: 'They default in month eight. You own a half-built car park.',
          cashSeconds: -420,
          morale: -0.15,
          addTag: { tag: 'bad_book', seconds: 900 },
        },
      },
      {
        label: 'Approve with covenants',
        hint: 'Smaller fee, protected',
        odds: 0.88,
        good: { text: 'Tighter terms, smaller fee, and you sleep at night.', cashSeconds: 160 },
        bad: { text: 'They take the deal to a competitor who asked fewer questions.', cashSeconds: -60 },
      },
      {
        label: 'Decline',
        hint: 'No risk, no reward',
        odds: 1,
        good: { text: 'You pass. The credit committee agrees it was the right call.', morale: 0.05 },
        bad: { text: '', morale: 0.05 },
      },
    ],
  },
  {
    id: 'bank_workout',
    category: 'bank',
    title: 'The Loan Book Needs Cleaning',
    body: 'Non-performing loans have crept past what the committee is comfortable with, and the auditors will notice before the quarter closes.',
    requiresTag: 'bad_book',
    choices: [
      {
        label: 'Sell the bad book',
        hint: 'Instant, at a discount',
        odds: 0.9,
        good: { text: 'A distressed fund takes it at sixty cents. Painful, clean, done.', cashSeconds: -140, removeTag: 'bad_book' },
        bad: { text: 'The only bidder knows you are forced and prices accordingly.', cashSeconds: -280, removeTag: 'bad_book' },
      },
      {
        label: 'Work them out yourself',
        hint: 'Slow, better recovery',
        odds: 0.6,
        good: { text: 'Patient restructuring recovers far more than a fire sale would have.', cashSeconds: 200, removeTag: 'bad_book' },
        bad: { text: 'Two years of forbearance and the same losses, later.', cashSeconds: -320 },
      },
    ],
  },
  {
    id: 'bank_regulator',
    category: 'bank',
    title: 'Regulatory Examination',
    body: 'The examiners are in for two weeks. Your capital ratios are fine. Your documentation is a different conversation.',
    choices: [
      {
        label: 'Full cooperation',
        hint: 'Slow, safe',
        odds: 0.85,
        good: { text: 'Minor findings, remediation plan accepted, clean bill of health.', cashSeconds: -100, morale: 0.05 },
        bad: {
          text: 'Cooperation surfaces problems you did not know you had. Consent order.',
          cashSeconds: -300,
          addTag: { tag: 'consent_order', seconds: 1200 },
          chain: { cardId: 'bank_remediation', delay: 280 },
        },
      },
      {
        label: 'Lawyer up',
        hint: 'Expensive, combative',
        odds: 0.6,
        good: { text: 'Counsel narrows the scope dramatically. The exam closes early and quietly.', cashSeconds: -140 },
        bad: {
          text: 'Stonewalling invites a broader review. This will take a year.',
          cashSeconds: -450,
          morale: -0.2,
          addTag: { tag: 'consent_order', seconds: 1200 },
          chain: { cardId: 'bank_remediation', delay: 280 },
        },
      },
    ],
  },
  {
    id: 'bank_remediation',
    category: 'bank',
    title: 'Under a Consent Order',
    body: 'Every new product needs approval, every process needs documenting, and a monitor sits in on your committee meetings.',
    chainOnly: true,
    choices: [
      {
        label: 'Over-comply spectacularly',
        hint: 'Expensive, ends it early',
        odds: 0.85,
        good: { text: 'You exceed every requirement. The order lifts a year ahead of schedule.', cashSeconds: -220, removeTag: 'consent_order', morale: 0.15 },
        bad: { text: 'Enormous spend, and the monitor keeps finding more to look at.', cashSeconds: -340 },
      },
      {
        label: 'Do the minimum',
        hint: 'Cheap, drags on',
        odds: 0.6,
        good: { text: 'You tick every box slowly and it eventually expires.', cashSeconds: -80, removeTag: 'consent_order' },
        bad: { text: 'Minimum compliance is read as bad faith. The order is extended.', cashSeconds: -260, morale: -0.2 },
      },
    ],
  },
  {
    id: 'bank_rates',
    category: 'bank',
    title: 'Rate Decision Ahead',
    body: 'The central bank meets Thursday. Your treasury desk wants to position the book one way or the other, hard.',
    choices: [
      {
        label: 'Position for a cut',
        hint: 'Directional bet',
        odds: 0.5,
        good: { text: 'They cut. The bond book rips and the desk takes a victory lap.', cashSeconds: 420 },
        bad: { text: 'They hold. The position bleeds and the desk head goes very quiet.', cashSeconds: -300 },
      },
      {
        label: 'Stay neutral',
        hint: 'Boring, safe',
        odds: 1,
        good: { text: 'Duration matched, risk flat. You make exactly what you planned to make.', cashSeconds: 60 },
        bad: { text: '', cashSeconds: 60 },
      },
    ],
  },
  {
    id: 'bank_fraud',
    category: 'bank',
    title: 'Suspicious Transfers',
    body: 'Compliance flagged a pattern across forty accounts. Freezing them will infuriate legitimate customers if the pattern is noise.',
    choices: [
      {
        label: 'Freeze immediately',
        hint: 'Safe, angers customers',
        odds: 0.8,
        good: { text: 'You catch a live fraud ring. Regulators note your systems approvingly.', cashSeconds: 140, luck: 2 },
        bad: { text: 'False positives. Forty furious customers and a viral complaint thread.', cashSeconds: -180, morale: -0.15 },
      },
      {
        label: 'Monitor quietly',
        hint: 'Gamble on more data',
        odds: 0.55,
        good: { text: 'A week of surveillance builds an airtight case. Every cent recovered.', cashSeconds: 260 },
        bad: { text: 'The funds are gone by Friday. The write-off is entirely yours.', cashSeconds: -400 },
      },
    ],
  },
  {
    id: 'bank_wealth',
    category: 'bank',
    title: 'Private Wealth Division',
    body: 'You could stand up a private bank for ultra-high-net-worth clients. It requires poaching an entire team.',
    minLevel: 3,
    choices: [
      {
        label: 'Poach the team',
        hint: 'Enormous cost, sticky revenue',
        odds: 0.7,
        good: { text: 'They bring their book with them. Fee income with almost no capital cost.', boost: { label: 'Private Bank', kind: 'income', power: 1.75, duration: 1200, scope: 'business' } },
        bad: { text: 'Their non-competes hold. You paid signing bonuses for people who cannot work.', cashSeconds: -500 },
      },
      {
        label: 'Build it slowly',
        hint: 'Cheap, gradual',
        odds: 0.9,
        good: { text: 'Two advisors and a plan. It compounds quietly for years.', boost: { label: 'Wealth Desk', kind: 'income', power: 1.25, duration: 1500, scope: 'business' } },
        bad: { text: 'Without a marquee name nobody moves their money. Slow start.', cashSeconds: -80 },
      },
    ],
  },
  {
    id: 'bank_run',
    category: 'bank',
    title: 'Deposit Flight',
    body: 'A rumour is circulating on social media. Withdrawals are running at eleven times normal and it is only Tuesday.',
    minLevel: 2,
    choices: [
      {
        label: 'Publicly guarantee deposits',
        hint: 'Expensive, decisive',
        odds: 0.85,
        good: { text: 'A calm, specific statement with real numbers. The flight stops within a day.', cashSeconds: -240, morale: 0.15 },
        bad: { text: 'Reassurance reads as panic. The outflow accelerates.', cashSeconds: -520, morale: -0.25 },
      },
      {
        label: 'Say nothing and hold',
        hint: 'Risky silence',
        odds: 0.45,
        good: { text: 'The rumour burns out on its own. Deposits return within the week.', cashSeconds: -40 },
        bad: { text: 'Silence confirms the story. You sell assets at fire-sale prices to meet withdrawals.', cashSeconds: -700, morale: -0.35 },
      },
    ],
  },
  {
    id: 'bank_branch',
    category: 'bank',
    title: 'Close The Branches?',
    body: 'Footfall is down 70% in five years. The branches are expensive, beloved by a shrinking group of customers, and politically radioactive to close.',
    minLevel: 2,
    choices: [
      {
        label: 'Close the quiet ones',
        hint: 'Saves money, costs goodwill',
        odds: 0.8,
        good: { text: 'A significant cost line disappears and almost nobody actually leaves.', boost: { label: 'Lean Network', kind: 'income', power: 1.45, duration: 1200, scope: 'business' }, morale: -0.1 },
        bad: { text: 'Local campaigns, a parliamentary question, and a deposit outflow.', cashSeconds: -260, morale: -0.2 },
      },
      {
        label: 'Keep them and cut costs elsewhere',
        hint: 'Expensive, popular',
        odds: 0.85,
        good: { text: 'You become the bank that kept its branches. Older, wealthier customers notice.', boost: { label: 'Still On The High Street', kind: 'income', power: 1.25, duration: 1500, scope: 'business' }, luck: 3 },
        bad: { text: 'The cost base stays and the customers still went online.', cashSeconds: -180 },
      },
    ],
  },
  {
    id: 'bank_fintech',
    category: 'bank',
    title: 'A Fintech Is Eating Your Lunch',
    body: 'An app with no branches and no legacy systems has taken a fifth of your under-thirties in eighteen months.',
    choices: [
      {
        label: 'Buy them',
        hint: 'Enormous price',
        odds: 0.7,
        good: { text: 'You acquire the product and, crucially, the team that built it.', boost: { label: 'Acquired Innovation', kind: 'income', power: 1.85, duration: 1200, scope: 'business' } },
        bad: { text: 'You buy them, integrate them into your processes, and destroy what worked.', cashSeconds: -420, morale: -0.2 },
      },
      {
        label: 'Build a rival',
        hint: 'Cheaper, slower',
        odds: 0.5,
        good: { text: 'A skunkworks team ships something genuinely good. Customers come back.', boost: { label: 'Digital Bank', kind: 'income', power: 1.6, duration: 1200, scope: 'business' } },
        bad: { text: 'Two years and a committee produce a worse version of their app.', cashSeconds: -300, morale: -0.2 },
      },
    ],
  },
  {
    id: 'bank_mortgage',
    category: 'bank',
    title: 'Mortgage Book Decision',
    body: 'Housing is hot. You could write a great deal of mortgage business right now, at prices that assume it stays hot.',
    choices: [
      {
        label: 'Write aggressively',
        hint: 'Volume now, risk later',
        odds: 0.55,
        good: { text: 'The market holds. The book performs and the volume was enormous.', cashSeconds: 380 },
        bad: { text: 'The market turns and you are the last lender holding the top of it.', cashSeconds: -460, addTag: { tag: 'bad_book', seconds: 1200 } },
      },
      {
        label: 'Keep underwriting tight',
        hint: 'Less volume, safer',
        odds: 0.95,
        good: { text: 'Modest volume, immaculate book. Dull and correct.', cashSeconds: 110 },
        bad: { text: 'Competitors take the market and your board asks why.', cashSeconds: -70, morale: -0.1 },
      },
    ],
  },
  {
    id: 'bank_aml',
    category: 'bank',
    title: 'A Client You Should Not Have',
    body: 'Compliance has flagged a long-standing, extremely profitable client whose source of funds nobody has ever satisfactorily explained.',
    choices: [
      {
        label: 'Exit the relationship',
        hint: 'Costly, correct',
        odds: 0.95,
        good: { text: 'You close the accounts. The revenue hurts. Nothing ever comes back to you.', cashSeconds: -220, luck: 5 },
        bad: { text: 'They sue for wrongful termination and the details become public anyway.', cashSeconds: -300 },
      },
      {
        label: 'Keep banking them',
        hint: 'Profitable, dangerous',
        odds: 0.45,
        good: { text: 'Nothing happens. The fees keep arriving.', cashSeconds: 280 },
        bad: { text: 'An enforcement action, a fine, and your name in the reporting.', cashSeconds: -650, morale: -0.3, addTag: { tag: 'consent_order', seconds: 1200 } },
      },
    ],
  },
  {
    id: 'bank_outage',
    category: 'bank',
    title: 'Payments Are Down',
    body: 'The core banking platform has failed on the last Friday of the month. Salaries are not arriving and the phones have melted.',
    choices: [
      {
        label: 'Compensate everyone generously',
        hint: 'Expensive, rebuilds trust',
        odds: 0.9,
        good: { text: 'Fast, generous, no quibbling. Customers forgive it almost entirely.', cashSeconds: -230, morale: 0.15 },
        bad: { text: 'The gesture is swamped by the scale of the failure.', cashSeconds: -340, morale: -0.15 },
      },
      {
        label: 'Handle claims case by case',
        hint: 'Cheaper, slower',
        odds: 0.6,
        good: { text: 'Most people never claim. The cost is a fraction of a blanket payout.', cashSeconds: -90 },
        bad: { text: 'A regulator takes an interest in how claims were being handled.', cashSeconds: -400, addTag: { tag: 'consent_order', seconds: 900 } },
      },
    ],
  },
  {
    id: 'bank_ceo_pay',
    category: 'bank',
    title: 'The Pay Vote',
    body: 'The remuneration report goes to shareholders next week and the numbers, in the current climate, look exactly as bad as they are.',
    minLevel: 3,
    choices: [
      {
        label: 'Cut the bonus pool',
        hint: 'Good optics, angry desks',
        odds: 0.75,
        good: { text: 'The vote passes comfortably and the press moves on.', cashSeconds: 90, morale: -0.15 },
        bad: { text: 'Three revenue-generating teams leave for a competitor within a quarter.', cashSeconds: -280, staff: -2, morale: -0.25 },
      },
      {
        label: 'Defend it',
        hint: 'Keeps talent, invites headlines',
        odds: 0.6,
        good: { text: 'You make the case and win the vote. The desks notice you backed them.', morale: 0.25, boost: { label: 'Talent Retained', kind: 'income', power: 1.3, duration: 900, scope: 'business' } },
        bad: { text: 'A shareholder revolt, a week of headlines, and the bonus is cut anyway.', cashSeconds: -220, morale: -0.2 },
      },
    ],
  },
  {
    id: 'bank_crypto',
    category: 'bank',
    title: 'Clients Want Crypto Custody',
    body: 'Institutional clients are asking you to hold digital assets. The fees are excellent. The operational risk is novel and enormous.',
    minLevel: 3,
    choices: [
      {
        label: 'Build custody',
        hint: 'High fee, high risk',
        odds: 0.6,
        good: { text: 'You are early, credible, and charging for it. Fee income climbs sharply.', boost: { label: 'Digital Custody', kind: 'income', power: 1.9, duration: 1200, scope: 'business' } },
        bad: { text: 'A key management incident. Nothing lost, but the review is brutal.', cashSeconds: -380, addTag: { tag: 'consent_order', seconds: 900 } },
      },
      {
        label: 'Stay out of it',
        hint: 'No risk, no fees',
        odds: 1,
        good: { text: 'You decline politely and watch from a safe distance.', morale: 0.05 },
        bad: { text: '', morale: 0.05 },
      },
    ],
  },
  {
    id: 'bank_merger',
    category: 'bank',
    title: 'A Merger Of Equals',
    body: 'A similarly sized bank proposes a merger. Both boards would keep seats, which is usually where these things go wrong.',
    minLevel: 4,
    choices: [
      {
        label: 'Do the deal',
        hint: 'Scale, integration risk',
        odds: 0.6,
        good: { text: 'The integration is disciplined. The combined bank is far stronger than either half.', boost: { label: 'Merged', kind: 'income', power: 2.1, duration: 1500, scope: 'business' } },
        bad: { text: 'Two cultures, two core systems, and three years of nobody knowing who decides.', cashSeconds: -500, morale: -0.3 },
      },
      {
        label: 'Stay independent',
        hint: 'Smaller, coherent',
        odds: 1,
        good: { text: 'You stay your own bank. Everyone knows who is in charge.', morale: 0.15, cashSeconds: 60 },
        bad: { text: '', morale: 0.15, cashSeconds: 60 },
      },
    ],
  },
  {
    id: 'bank_stress_test',
    category: 'bank',
    title: 'Stress Test Results',
    body: 'The scenario assumes a severe recession and a property crash. Your capital survives it, but not comfortably enough for the regulator.',
    minLevel: 2,
    choices: [
      {
        label: 'Raise capital now',
        hint: 'Dilutive, safe',
        odds: 0.9,
        good: { text: 'You raise on your own terms while you still have them.', cashSeconds: -150, removeTag: 'bad_book' },
        bad: { text: 'The raise is read as distress and the price you get reflects that.', cashSeconds: -280 },
      },
      {
        label: 'Shrink the balance sheet',
        hint: 'Slower, no dilution',
        odds: 0.75,
        good: { text: 'You sell down risk-weighted assets and pass on the retest.', cashSeconds: -60 },
        bad: { text: 'Selling the good assets is easy; the ratio barely moves.', cashSeconds: -220, morale: -0.15 },
      },
    ],
  },
  {
    id: 'bank_relationship',
    category: 'bank',
    title: 'An Old Client Needs Help',
    body: 'A family business you have banked for forty years is in trouble. The credit committee says no. The relationship manager is in your office.',
    choices: [
      {
        label: 'Back them',
        hint: 'Against the model',
        odds: 0.6,
        good: { text: 'They trade through it and never bank anywhere else again. Nor do their friends.', cashSeconds: 260, luck: 6, morale: 0.2 },
        bad: { text: 'They fail anyway and you explain to the committee why you overrode them.', cashSeconds: -320, addTag: { tag: 'bad_book', seconds: 900 } },
      },
      {
        label: 'Follow the model',
        hint: 'Correct, cold',
        odds: 1,
        good: { text: 'The answer is no. It is the right answer and it feels terrible.', morale: -0.1, cashSeconds: 40 },
        bad: { text: '', morale: -0.1, cashSeconds: 40 },
      },
    ],
  },
];
