import type { EventCardDef } from '../../types';

/** Development deck. Slow, enormous, unstoppable once the cranes are up. */

export const DEVCO_CARDS: EventCardDef[] = [
  {
    id: 'dev_permit',
    category: 'devco',
    title: 'Planning Permission Stalled',
    body: 'The council has sat on your application for seven months. A consultant says they know who to talk to.',
    excludesTag: 'consented',
    choices: [
      {
        label: 'Hire the consultant',
        hint: 'Expensive, effective',
        odds: 0.8,
        good: { text: 'Approved within a month. Whatever they did, it worked and it was legal.', cashSeconds: -160, addTag: { tag: 'consented', seconds: 1200 } },
        bad: { text: 'They took the fee and achieved nothing. The application sits where it was.', cashSeconds: -260 },
      },
      {
        label: 'Redesign to fit policy',
        hint: 'Slow, certain',
        odds: 0.95,
        good: { text: 'Two floors shorter, fully compliant, approved without objection.', cashSeconds: -100, morale: 0.05, addTag: { tag: 'consented', seconds: 1200 } },
        bad: { text: 'Even the compliant scheme draws objections. Another six months.', cashSeconds: -200 },
      },
    ],
  },
  {
    id: 'dev_contractor',
    category: 'devco',
    title: 'Main Contractor in Trouble',
    body: 'Your builder is 60% through the tower and rumoured to be insolvent. Their subcontractors have not been paid in five weeks.',
    choices: [
      {
        label: 'Pay the subs directly',
        hint: 'Costly, keeps the site moving',
        odds: 0.85,
        good: { text: 'The site keeps working. You take over the contract and finish on schedule.', cashSeconds: -300, morale: 0.1 },
        bad: { text: 'The administrator claws back the direct payments. You pay twice.', cashSeconds: -600, addTag: { tag: 'delayed', seconds: 900 } },
      },
      {
        label: 'Call the bond',
        hint: 'Slow, protected',
        odds: 0.75,
        good: { text: 'The surety appoints a replacement. Four months lost, no money lost.', cashSeconds: -160, addTag: { tag: 'delayed', seconds: 600 } },
        bad: { text: 'The bond is disputed. The site sits idle through the wet season.', cashSeconds: -480, morale: -0.2, addTag: { tag: 'delayed', seconds: 1200 } },
      },
    ],
  },
  {
    id: 'dev_delay_recovery',
    category: 'devco',
    title: 'Behind Programme',
    body: 'The schedule has slipped a full quarter. Finance costs accrue daily and the presale buyers have completion dates in their contracts.',
    requiresTag: 'delayed',
    choices: [
      {
        label: 'Accelerate at any cost',
        hint: 'Enormous spend, back on track',
        odds: 0.8,
        good: { text: 'Double shifts and premium rates claw the programme back. Nobody gets a refund.', cashSeconds: -300, removeTag: 'delayed' },
        bad: { text: 'You spend the money and recover three weeks of a thirteen-week slip.', cashSeconds: -420 },
      },
      {
        label: 'Renegotiate with buyers',
        hint: 'Cheaper, reputational cost',
        odds: 0.7,
        good: { text: 'Most buyers accept a discount to wait. A few walk, which you can live with.', cashSeconds: -140, removeTag: 'delayed', morale: -0.1 },
        bad: { text: 'A third of the buyers rescind and the sales agent stops returning calls.', cashSeconds: -380, morale: -0.25 },
      },
    ],
  },
  {
    id: 'dev_presale',
    category: 'devco',
    title: 'Presale Launch',
    body: 'Units go on sale Saturday. You can price to sell out fast or hold for the number you think the market will bear.',
    choices: [
      {
        label: 'Price to sell out',
        hint: 'Fast cash, lower total',
        odds: 0.95,
        good: { text: 'Sold out in a weekend. The bank is delighted and the cash lands early.', cashSeconds: 320 },
        bad: { text: 'Even priced keenly the market is thin. Half the building is unsold.', cashSeconds: 80 },
      },
      {
        label: 'Hold for top dollar',
        hint: 'Patient, higher ceiling',
        odds: 0.55,
        good: { text: 'You hold the line and the market comes to you. Record price per square foot.', cashSeconds: 620 },
        bad: { text: 'Sentiment turns while you wait. You discount harder than you would have needed to.', cashSeconds: -180 },
      },
    ],
  },
  {
    id: 'dev_heritage',
    category: 'devco',
    title: 'Heritage Objection',
    body: 'A campaign group has applied to list the Victorian frontage on your site. Demolition is scheduled for Monday.',
    choices: [
      {
        label: 'Incorporate the facade',
        hint: 'Costly, universally praised',
        odds: 0.9,
        good: { text: 'Facade retention adds cost and enormous goodwill. The scheme wins an award.', cashSeconds: -220, luck: 3, morale: 0.15 },
        bad: { text: 'Retention proves structurally impossible after you committed to it publicly.', cashSeconds: -380, addTag: { tag: 'delayed', seconds: 900 } },
      },
      {
        label: 'Demolish before the listing',
        hint: 'Fast, ugly',
        odds: 0.6,
        good: { text: 'Cleared by Tuesday. Entirely legal, thoroughly unpopular, project on schedule.', cashSeconds: 60, morale: -0.15 },
        bad: { text: 'An emergency injunction lands Sunday night. Now you are in court and in the papers.', cashSeconds: -500, morale: -0.3, addTag: { tag: 'delayed', seconds: 1200 } },
      },
    ],
  },
  {
    id: 'dev_anchor',
    category: 'devco',
    title: 'Anchor Tenant Negotiation',
    body: 'A major retailer will anchor the ground floor, but they want fifteen years of rent-free fit-out and naming rights.',
    choices: [
      {
        label: 'Give them the terms',
        hint: 'Cheap rent, fills the building',
        odds: 0.85,
        good: { text: 'Their name on the building fills every other unit at a premium.', boost: { label: 'Anchor Secured', kind: 'income', power: 1.5, duration: 1200, scope: 'business' } },
        bad: { text: 'They downsize nationally two years later and hand back the space.', cashSeconds: -300 },
      },
      {
        label: 'Hold out for market rent',
        hint: 'Risky',
        odds: 0.5,
        good: { text: 'They blink. Full rent, shorter term, better building.', cashSeconds: 400 },
        bad: { text: 'They walk. An empty ground floor makes the whole scheme look failed.', cashSeconds: -360, morale: -0.15 },
      },
    ],
  },
  {
    id: 'dev_landbank',
    category: 'devco',
    title: 'Land Bank Opportunity',
    body: 'Three adjoining sites are available from a distressed seller. Assembled they are worth far more than the sum. Assembling them takes capital and nerve.',
    minLevel: 3,
    choices: [
      {
        label: 'Buy all three',
        hint: 'Heavy capital, big prize',
        odds: 0.7,
        good: { text: 'Assembled and rezoned. The combined site is worth triple what you paid.', boost: { label: 'Site Assembly', kind: 'income', power: 2.0, duration: 1200, scope: 'business' } },
        bad: { text: 'The middle owner refuses to sell at the last moment. You own two useless plots.', cashSeconds: -650 },
      },
      {
        label: 'Take the best one',
        hint: 'Modest, safe',
        odds: 0.9,
        good: { text: 'One good site at a distressed price. Unglamorous and profitable.', cashSeconds: 180 },
        bad: { text: 'Ground conditions are worse than the survey suggested. Remediation is expensive.', cashSeconds: -200 },
      },
    ],
  },
  {
    id: 'dev_contamination',
    category: 'devco',
    title: 'Something In The Ground',
    body: 'The site investigation found contamination the vendor did not disclose. Remediation is expensive and the programme assumed clean ground.',
    choices: [
      {
        label: 'Remediate fully',
        hint: 'Expensive, unblocks everything',
        odds: 0.9,
        good: { text: 'Dug out, treated, signed off. Expensive and completely finished.', cashSeconds: -280 },
        bad: { text: 'The plume extends under the neighbouring site. This just got much bigger.', cashSeconds: -520, addTag: { tag: 'delayed', seconds: 1200 } },
      },
      {
        label: 'Sue the vendor',
        hint: 'Slow, possibly free',
        odds: 0.55,
        good: { text: 'Non-disclosure is clear. They fund the entire remediation.', cashSeconds: -60 },
        bad: { text: 'The contract said "sold as seen" in a clause you should have read.', cashSeconds: -420, addTag: { tag: 'delayed', seconds: 900 } },
      },
    ],
  },
  {
    id: 'dev_affordable',
    category: 'devco',
    title: 'Affordable Housing Requirement',
    body: 'The authority wants 35% affordable. Your viability assessment says 12%. Both numbers were produced by consultants who knew what was wanted.',
    choices: [
      {
        label: 'Fight the assessment',
        hint: 'Costly, protects margin',
        odds: 0.6,
        good: { text: 'The viability case holds at 15%. The scheme stays profitable.', cashSeconds: -120 },
        bad: { text: 'An independent reviewer sides with the council. You build 35% and eat it.', cashSeconds: -400, addTag: { tag: 'delayed', seconds: 900 } },
      },
      {
        label: 'Accept and build it',
        hint: 'Lower margin, fast consent',
        odds: 0.95,
        good: { text: 'Consent lands in weeks and the authority becomes an ally on your next scheme.', cashSeconds: -180, luck: 5, addTag: { tag: 'consented', seconds: 1200 } },
        bad: { text: 'You accepted and it still took a year.', cashSeconds: -260 },
      },
    ],
  },
  {
    id: 'dev_crane',
    category: 'devco',
    title: 'A Crane Came Down',
    body: 'Nobody was hurt. The site is closed, the investigators are in, and there is drone footage on every news channel.',
    choices: [
      {
        label: 'Full independent investigation',
        hint: 'Costly, restores trust',
        odds: 0.85,
        good: { text: 'Transparent, thorough, and published. The industry treats you as the good example.', cashSeconds: -280, luck: 5, morale: 0.15, addTag: { tag: 'delayed', seconds: 600 } },
        bad: { text: 'The investigation finds your own procurement was the cause.', cashSeconds: -520, morale: -0.3, addTag: { tag: 'delayed', seconds: 1200 } },
      },
      {
        label: 'Blame the subcontractor',
        hint: 'Fast, cheap, corrosive',
        odds: 0.5,
        good: { text: 'Liability lands elsewhere and the site reopens in a fortnight.', cashSeconds: -90, morale: -0.2 },
        bad: { text: 'The subcontractor has records showing you rejected their safety costings.', cashSeconds: -600, morale: -0.35, addTag: { tag: 'delayed', seconds: 1200 } },
      },
    ],
  },
  {
    id: 'dev_finance',
    category: 'devco',
    title: 'Development Finance Renewal',
    body: 'The facility matures in sixty days and the lender has become noticeably less enthusiastic about your sector.',
    choices: [
      {
        label: 'Refinance with a debt fund',
        hint: 'Expensive, certain',
        odds: 0.9,
        good: { text: 'Priced brutally but signed in three weeks. The site keeps building.', cashSeconds: -190 },
        bad: { text: 'Even the debt fund wants more equity in first.', cashSeconds: -330 },
      },
      {
        label: 'Bring in an equity partner',
        hint: 'Cheaper money, shared upside',
        odds: 0.7,
        good: { text: 'A partner takes 30% of the profit and all of the financing pressure.', cashSeconds: 140 },
        bad: { text: 'Diligence drags past the maturity date and the lender charges default rates.', cashSeconds: -420, addTag: { tag: 'delayed', seconds: 900 } },
      },
    ],
  },
  {
    id: 'dev_neighbours',
    category: 'devco',
    title: 'The Neighbours Have Organised',
    body: 'Right to light, construction hours, and a residents\' association with a lawyer who used to do this professionally.',
    choices: [
      {
        label: 'Settle with them',
        hint: 'Costly, removes the risk',
        odds: 0.9,
        good: { text: 'Compensation agreed, hours agreed, objections withdrawn. Clean.', cashSeconds: -170, addTag: { tag: 'consented', seconds: 900 } },
        bad: { text: 'Settling with some emboldens the rest. A second group forms.', cashSeconds: -290 },
      },
      {
        label: 'Litigate',
        hint: 'Slow, might win outright',
        odds: 0.5,
        good: { text: 'The claim fails on the facts. You build exactly what you designed.', cashSeconds: -80 },
        bad: { text: 'An injunction on working hours adds four months to the programme.', cashSeconds: -400, addTag: { tag: 'delayed', seconds: 1200 } },
      },
    ],
  },
  {
    id: 'dev_bulk_sale',
    category: 'devco',
    title: 'An Institution Wants The Whole Building',
    body: 'A pension fund will buy every unit at once, today, at a discount to what you would get selling them individually over two years.',
    choices: [
      {
        label: 'Sell in bulk',
        hint: 'Certain, discounted',
        odds: 1,
        good: { text: 'One buyer, one completion, no sales suite. The cash lands immediately.', cashSeconds: 420 },
        bad: { text: '', cashSeconds: 420 },
      },
      {
        label: 'Sell unit by unit',
        hint: 'Slower, more total',
        odds: 0.6,
        good: { text: 'Two years of individual sales at full price. Considerably more money.', cashSeconds: 760 },
        bad: { text: 'The market softens halfway through and you finish at bulk prices anyway.', cashSeconds: 120 },
      },
    ],
  },
  {
    id: 'dev_architect',
    category: 'devco',
    title: 'A Signature Architect',
    body: 'A very famous practice would take the commission. Their fee is four times normal and their buildings end up on postcards.',
    minLevel: 3,
    choices: [
      {
        label: 'Commission them',
        hint: 'Enormous fee, enormous value',
        odds: 0.7,
        good: { text: 'The building becomes a landmark and every unit prices at a premium.', boost: { label: 'Landmark Scheme', kind: 'income', power: 1.9, duration: 1500, scope: 'business' }, luck: 5 },
        bad: { text: 'A magnificent design that cannot be built to budget. Redesign from scratch.', cashSeconds: -420, addTag: { tag: 'delayed', seconds: 900 } },
      },
      {
        label: 'Use your usual practice',
        hint: 'Reliable, unremarkable',
        odds: 0.95,
        good: { text: 'Delivered on budget, on programme, and nobody will ever photograph it.', cashSeconds: 130 },
        bad: { text: 'Competent and dull. It sells slowly against better-looking competition.', cashSeconds: -110 },
      },
    ],
  },
  {
    id: 'dev_labour',
    category: 'devco',
    title: 'Nobody Can Find Trades',
    body: 'Bricklayers, electricians, groundworkers — everyone is on somebody else\'s site and the rates have gone vertical.',
    choices: [
      {
        label: 'Pay above market',
        hint: 'Costly, keeps programme',
        odds: 0.9,
        good: { text: 'You buy the labour and hold the programme. Margin thinner, dates intact.', cashSeconds: -230 },
        bad: { text: 'You pay the premium and they leave for someone paying more.', cashSeconds: -360, addTag: { tag: 'delayed', seconds: 900 } },
      },
      {
        label: 'Train your own',
        hint: 'Slow, permanent',
        odds: 0.7,
        good: { text: 'An apprenticeship programme takes two years and then you never have this problem again.', cashSeconds: -160, boost: { label: 'Own Workforce', kind: 'income', power: 1.5, duration: 1500, scope: 'business' } },
        bad: { text: 'You train them and a competitor hires them the week they qualify.', cashSeconds: -250 },
      },
    ],
  },
  {
    id: 'dev_consented_sale',
    category: 'devco',
    title: 'Sell The Consent?',
    body: 'With planning permission in hand the site is worth far more than you paid. Another developer would buy it now and build it themselves.',
    requiresTag: 'consented',
    choices: [
      {
        label: 'Sell the consented site',
        hint: 'Immediate profit, no build risk',
        odds: 1,
        good: { text: 'The uplift from consent alone is enormous, and someone else takes the build risk.', cashSeconds: 480, removeTag: 'consented' },
        bad: { text: '', cashSeconds: 480, removeTag: 'consented' },
      },
      {
        label: 'Build it yourself',
        hint: 'Far more, far slower',
        odds: 0.7,
        good: { text: 'You take the whole development profit rather than a slice of it.', boost: { label: 'Built It Ourselves', kind: 'income', power: 2.0, duration: 1500, scope: 'business' } },
        bad: { text: 'Costs inflate through the build and the margin ends up thinner than the consent was worth.', cashSeconds: -300, addTag: { tag: 'delayed', seconds: 900 } },
      },
    ],
  },
  {
    id: 'dev_masterplan',
    category: 'devco',
    title: 'A Whole District',
    body: 'The city wants a masterplan developer for forty acres. It is a decade of work, a fortune in fees, and a level of political exposure you have not had before.',
    minLevel: 5,
    choices: [
      {
        label: 'Bid for it',
        hint: 'Career-defining',
        odds: 0.6,
        good: {
          text: 'You win it. A decade of pipeline and your name on the skyline.',
          boost: { label: 'Masterplan Developer', kind: 'income', power: 2.4, duration: 1500, scope: 'business' },
          luck: 8,
        },
        bad: { text: 'A very expensive bid, a political shortlist, and second place.', cashSeconds: -420, morale: -0.2 },
      },
      {
        label: 'Stay with single sites',
        hint: 'Smaller, controllable',
        odds: 1,
        good: { text: 'You keep doing the thing you are good at, one site at a time.', cashSeconds: 90, morale: 0.1 },
        bad: { text: '', cashSeconds: 90, morale: 0.1 },
      },
    ],
  },
  {
    id: 'dev_interest',
    category: 'devco',
    title: 'Rates Moved Against You',
    body: 'The facility is floating rate and the central bank has been busy. Finance costs on the scheme have risen by half.',
    choices: [
      {
        label: 'Hedge the exposure',
        hint: 'Costs now, caps the damage',
        odds: 0.85,
        good: { text: 'The swap caps your exposure just before the next move up.', cashSeconds: -110 },
        bad: { text: 'You hedge at the top and rates fall back within a quarter.', cashSeconds: -210 },
      },
      {
        label: 'Sell units early to repay',
        hint: 'Discounts now, kills the debt',
        odds: 0.8,
        good: { text: 'Early sales at a discount clear the facility. Lower profit, no risk.', cashSeconds: 140 },
        bad: { text: 'You discounted into a soft week and still carry most of the debt.', cashSeconds: -230 },
      },
    ],
  },
];
