import type { EventCardDef } from '../../types';

/**
 * Empire-wide deck. These can surface at any business and mostly concern the
 * player rather than the operation — press, lawyers, rivals, and the personal
 * cost of running the whole thing.
 */

export const GENERAL_CARDS: EventCardDef[] = [
  {
    id: 'any_audit',
    category: 'any',
    title: 'Tax Audit',
    body: 'The revenue service has questions about a deduction from two years ago. Your accountant is "not worried, exactly".',
    choices: [
      {
        label: 'Settle quietly',
        hint: 'Pay and move on',
        odds: 1,
        good: { text: 'You pay the assessment and the file closes. Expensive peace.', cashSeconds: -120 },
        bad: { text: '', cashSeconds: -120 },
      },
      {
        label: 'Fight it',
        hint: 'Could win outright',
        odds: 0.55,
        good: { text: 'The deduction was legitimate and the ruling says so. Costs recovered.', cashSeconds: 90, luck: 2 },
        bad: { text: 'You lose, plus penalties, plus interest, plus the legal bill.', cashSeconds: -280 },
      },
    ],
  },
  {
    id: 'any_press',
    category: 'any',
    title: 'A Journalist Is Writing About You',
    body: 'A business magazine is profiling your empire. They want access, a photographer, and an honest answer about the debt.',
    choices: [
      {
        label: 'Give full access',
        hint: 'Big exposure',
        odds: 0.65,
        good: {
          text: 'A flattering cover story. Doors open that were locked last week.',
          boost: { label: 'Cover Story', kind: 'income', power: 1.3, duration: 480, scope: 'empire' },
          luck: 3,
          chain: { cardId: 'any_profile_fallout', delay: 340 },
        },
        bad: { text: 'They found the one bad quarter and led with it.', cashSeconds: -150, morale: -0.1 },
      },
      {
        label: 'Send a statement',
        hint: 'Controlled, dull',
        odds: 0.9,
        good: { text: 'Three careful paragraphs. Nothing gained, nothing lost.', morale: 0.03 },
        bad: { text: '"Declined to comment" reads badly in print.', cashSeconds: -60 },
      },
    ],
  },
  {
    id: 'any_profile_fallout',
    category: 'any',
    title: 'Everyone Read The Profile',
    body: 'Three funds, a rival, and someone from your old job have all been in touch. Attention is a resource with a short shelf life.',
    chainOnly: true,
    choices: [
      {
        label: 'Take the meetings',
        hint: 'Time spent, doors opened',
        odds: 0.75,
        good: { text: 'One of the three becomes a genuine partner. Worth the fortnight.', boost: { label: 'Well Introduced', kind: 'income', power: 1.5, duration: 900, scope: 'empire' }, luck: 5 },
        bad: { text: 'Two weeks of coffee with people who wanted to meet someone from a magazine.', cashSeconds: -120 },
      },
      {
        label: 'Get back to work',
        hint: 'Focus',
        odds: 1,
        good: { text: 'You let it pass and run the business instead. Nothing is lost that mattered.', cashSeconds: 80, morale: 0.1 },
        bad: { text: '', cashSeconds: 80, morale: 0.1 },
      },
    ],
  },
  {
    id: 'any_charity',
    category: 'any',
    title: 'Charity Gala Invitation',
    body: 'A table at the season\'s gala costs a fortune. The room will be full of people who could make you money.',
    choices: [
      {
        label: 'Buy the table',
        hint: 'Expensive networking',
        odds: 0.75,
        good: { text: 'You leave with two deals and a great deal of goodwill.', cashSeconds: -100, luck: 5, boost: { label: 'Well Connected', kind: 'income', power: 1.2, duration: 420, scope: 'empire' } },
        bad: { text: 'You spend the evening seated next to a man who sells industrial adhesive.', cashSeconds: -160 },
      },
      {
        label: 'Donate anonymously',
        hint: 'Cheaper, quiet',
        odds: 1,
        good: { text: 'The money does more good than your presence would have. Luck finds you anyway.', cashSeconds: -50, luck: 3 },
        bad: { text: '', cashSeconds: -50, luck: 3 },
      },
      {
        label: 'Decline',
        hint: 'Free',
        odds: 1,
        good: { text: 'You stay in and work. Nobody notices your absence.', cashSeconds: 0 },
        bad: { text: '', cashSeconds: 0 },
      },
    ],
  },
  {
    id: 'any_lawsuit',
    category: 'any',
    title: 'Someone Is Suing You',
    body: 'A former partner claims they were owed a share of a deal you closed without them. Their lawyer is good.',
    choices: [
      {
        label: 'Settle out of court',
        hint: 'Certain cost',
        odds: 1,
        good: { text: 'A cheque and a non-disclosure agreement. Gone by Friday.', cashSeconds: -200 },
        bad: { text: '', cashSeconds: -200 },
      },
      {
        label: 'Take it to trial',
        hint: 'Win big or lose big',
        odds: 0.5,
        good: { text: 'Dismissed with costs awarded to you. Word gets around that you do not fold.', cashSeconds: 180, luck: 4 },
        bad: { text: 'A judgment against you plus both sets of legal fees.', cashSeconds: -500, morale: -0.15 },
      },
    ],
  },
  {
    id: 'any_headhunt',
    category: 'any',
    title: 'A Rival Is Poaching Your People',
    body: 'A competitor has approached four of your best operators with offers well above market.',
    choices: [
      {
        label: 'Match every offer',
        hint: 'Costly retention',
        odds: 0.9,
        good: { text: 'All four stay. Payroll is heavier and the bench is intact.', cashSeconds: -180, morale: 0.2 },
        bad: { text: 'Two stay, two go anyway, and everyone now knows what the market pays.', cashSeconds: -180, morale: -0.1, staff: -1 },
      },
      {
        label: 'Counter with equity',
        hint: 'No cash, needs belief',
        odds: 0.6,
        good: { text: 'They believe in where this is going. Cheaper than cash and far stickier.', morale: 0.3, luck: 2 },
        bad: { text: 'Equity in a private company is not rent money. Three leave.', morale: -0.25, staff: -2 },
      },
    ],
  },
  {
    id: 'any_windfall',
    category: 'any',
    title: 'Unexpected Windfall',
    body: 'An old investment you had written off entirely has just paid out. There is a cheque on your desk and a decision to make.',
    choices: [
      {
        label: 'Bank it',
        hint: 'Straight cash',
        odds: 1,
        good: { text: 'Straight into the operating account. Boring and useful.', cashSeconds: 240 },
        bad: { text: '', cashSeconds: 240 },
      },
      {
        label: 'Reinvest it aggressively',
        hint: 'Compound it or lose it',
        odds: 0.6,
        good: { text: 'You put it all back to work and it doubles inside a quarter.', cashSeconds: 560 },
        bad: { text: 'The reinvestment goes sideways. Most of the windfall evaporates.', cashSeconds: -80 },
      },
      {
        label: 'Buy roll tokens with it',
        hint: 'Convert to luck',
        odds: 1,
        good: { text: 'You put the whole cheque into deal flow. Three opportunities land on your desk.', rolls: 3 },
        bad: { text: '', rolls: 3 },
      },
    ],
  },
  {
    id: 'any_mentor',
    category: 'any',
    title: 'An Old Mentor Calls',
    body: 'The person who gave you your first break wants a favour. It is not a small one and they are not asking twice.',
    choices: [
      {
        label: 'Do it, no questions',
        hint: 'Costly, builds fortune',
        odds: 1,
        good: { text: 'You handle it. They remember, and people like them have long memories.', cashSeconds: -180, luck: 8 },
        bad: { text: '', cashSeconds: -180, luck: 8 },
      },
      {
        label: 'Politely decline',
        hint: 'Free, closes a door',
        odds: 1,
        good: { text: 'They understand. They do not call again.', cashSeconds: 0, luck: -2 },
        bad: { text: '', cashSeconds: 0, luck: -2 },
      },
    ],
  },
  {
    id: 'any_insider',
    category: 'any',
    title: 'A Very Specific Tip',
    body: 'Someone at the gala mentioned, unprompted and in detail, what a listed company will announce on Thursday. They should not know that.',
    choices: [
      {
        label: 'Act on it',
        hint: 'Illegal. Profitable. Risky.',
        odds: 0.55,
        good: { text: 'The announcement lands exactly as described. Nobody asks how you knew.', cashSeconds: 480 },
        bad: { text: 'A regulator asks how you knew. The fine is larger than the trade.', cashSeconds: -600, morale: -0.2 },
      },
      {
        label: 'Report it',
        hint: 'Clean, quietly rewarding',
        odds: 1,
        good: { text: 'You report it. It costs you nothing and buys you a reputation that pays for years.', luck: 10 },
        bad: { text: '', luck: 10 },
      },
      {
        label: 'Forget you heard it',
        hint: 'Nothing happens',
        odds: 1,
        good: { text: 'You finish your drink and change the subject.', cashSeconds: 0 },
        bad: { text: '', cashSeconds: 0 },
      },
    ],
  },
  {
    id: 'any_expansion',
    category: 'any',
    title: 'Overseas Expansion Pitch',
    body: 'A local partner wants to bring your operation to their market. They know the regulators. You know nothing about the market.',
    choices: [
      {
        label: 'Fund the expansion',
        hint: 'Big spend, empire-wide upside',
        odds: 0.6,
        good: { text: 'It works. A second market, running itself, paying you monthly.', boost: { label: 'International', kind: 'income', power: 1.45, duration: 900, scope: 'empire' } },
        bad: { text: 'You misread the market completely and your partner keeps the deposit.', cashSeconds: -400 },
      },
      {
        label: 'License the brand instead',
        hint: 'Low risk, low reward',
        odds: 0.9,
        good: { text: 'They pay a royalty and take all the risk. Small, clean, permanent income.', boost: { label: 'Licensing Deal', kind: 'income', power: 1.15, duration: 1500, scope: 'empire' } },
        bad: { text: 'They run the brand badly and it takes a year to unwind the agreement.', cashSeconds: -140 },
      },
    ],
  },
  {
    id: 'any_burnout',
    category: 'any',
    title: 'You Have Not Slept Properly In Weeks',
    body: 'The empire runs, the numbers are good, and you feel terrible. Something has to give.',
    choices: [
      {
        label: 'Take two weeks off',
        hint: 'Costs income, restores everything',
        odds: 1,
        good: { text: 'You come back sharp. Decisions get better across the board.', cashSeconds: -150, luck: 6, morale: 0.25 },
        bad: { text: '', cashSeconds: -150, luck: 6, morale: 0.25 },
      },
      {
        label: 'Push through',
        hint: 'Free, and it shows',
        odds: 0.45,
        good: { text: 'You get away with it. This time.', cashSeconds: 60 },
        bad: { text: 'You make an expensive mistake that a rested person would not have made.', cashSeconds: -320, morale: -0.2 },
      },
    ],
  },
  {
    id: 'any_counterfeit',
    category: 'any',
    title: 'Someone Is Copying You',
    body: 'A competitor has cloned your branding almost exactly, down to the typeface. Customers are confused and some of them are theirs now.',
    choices: [
      {
        label: 'Sue for infringement',
        hint: 'Slow and expensive',
        odds: 0.7,
        good: { text: 'Injunction granted. They rebrand entirely at their own cost.', cashSeconds: -120, morale: 0.1 },
        bad: { text: 'Your trademark filing was weaker than you thought. Case dismissed.', cashSeconds: -280 },
      },
      {
        label: 'Out-execute them',
        hint: 'No legal fees, pure competition',
        odds: 0.65,
        good: { text: 'You ship better and faster. Customers sort it out for themselves.', boost: { label: 'Out-Executed', kind: 'income', power: 1.35, duration: 480, scope: 'empire' }, morale: 0.15 },
        bad: { text: 'They undercut you on price and take the low end of your market.', cashSeconds: -220 },
      },
    ],
  },
  {
    id: 'any_luckystreak',
    category: 'any',
    title: 'Everything Is Going Right',
    body: 'Three deals closed this week without a hitch. Your accountant used the word "unusual". Do you press the advantage?',
    choices: [
      {
        label: 'Press it hard',
        hint: 'Ride the streak',
        odds: 0.6,
        good: { text: 'The streak holds. Everything you touch this month works.', boost: { label: 'Hot Streak', kind: 'income', power: 1.9, duration: 360, scope: 'empire' }, rolls: 2 },
        bad: { text: 'The streak ends the moment you rely on it. Two deals collapse.', cashSeconds: -240 },
      },
      {
        label: 'Bank the gains',
        hint: 'Lock in',
        odds: 1,
        good: { text: 'You take the money off the table and stop tempting fate.', cashSeconds: 200, luck: 2 },
        bad: { text: '', cashSeconds: 200, luck: 2 },
      },
    ],
  },
  {
    id: 'any_rival_bid',
    category: 'any',
    title: 'A Rival Wants To Buy You Out',
    body: 'A competitor has made an unsolicited approach for the whole group. The number is serious and slightly insulting at the same time.',
    minLevel: 3,
    choices: [
      {
        label: 'Reject and go public about it',
        hint: 'Bold, invites a better offer',
        odds: 0.6,
        good: { text: 'Going public flushes out two more bidders. The price climbs sharply.', cashSeconds: 520, luck: 4 },
        bad: { text: 'No other bidder appears and you look like you were shopping yourself.', cashSeconds: -220, morale: -0.15 },
      },
      {
        label: 'Reject quietly',
        hint: 'No drama',
        odds: 1,
        good: { text: 'A polite no and nobody outside the room ever knows.', morale: 0.1 },
        bad: { text: '', morale: 0.1 },
      },
    ],
  },
  {
    id: 'any_data_leak',
    category: 'any',
    title: 'Customer Data Is On A Forum',
    body: 'Somebody has posted a sample and is asking for money not to post the rest. The sample is genuine.',
    choices: [
      {
        label: 'Disclose immediately',
        hint: 'Painful, correct',
        odds: 0.85,
        good: { text: 'You tell everyone before the leaker does. It costs money and buys enormous credibility.', cashSeconds: -240, luck: 5, morale: 0.1 },
        bad: { text: 'Full disclosure triggers a regulatory investigation on top of everything else.', cashSeconds: -420, morale: -0.2 },
      },
      {
        label: 'Pay them off',
        hint: 'Quiet, no guarantees',
        odds: 0.4,
        good: { text: 'The post disappears and nothing further surfaces. You will never be sure.', cashSeconds: -180 },
        bad: { text: 'They take the money and post it anyway, along with the fact that you paid.', cashSeconds: -600, morale: -0.3 },
      },
    ],
  },
  {
    id: 'any_family',
    category: 'any',
    title: 'A Relative Wants A Job',
    body: 'They are family, they are enthusiastic, and everyone in the business will know exactly how they got the role.',
    choices: [
      {
        label: 'Hire them properly',
        hint: 'Same process as anyone',
        odds: 0.75,
        good: { text: 'They interview, they earn it, and nobody resents them for it.', staff: 1, morale: 0.15 },
        bad: { text: 'They do not get through the process and family dinners are now difficult.', morale: -0.1, luck: -2 },
      },
      {
        label: 'Say no',
        hint: 'Awkward, clean',
        odds: 1,
        good: { text: 'You explain why. It is uncomfortable, brief, and the business stays a business.', morale: 0.08 },
        bad: { text: '', morale: 0.08 },
      },
    ],
  },
  {
    id: 'any_politician',
    category: 'any',
    title: 'A Politician Wants A Photograph',
    body: 'They would like to be photographed at one of your sites talking about jobs. There is no explicit ask attached, which is itself the ask.',
    choices: [
      {
        label: 'Host the visit',
        hint: 'Access, at a price',
        odds: 0.7,
        good: { text: 'The visit goes well and doors at the authority open noticeably faster afterwards.', luck: 5, boost: { label: 'Friends In Office', kind: 'income', power: 1.25, duration: 900, scope: 'empire' } },
        bad: { text: 'They lose office within the month and their opponent remembers the photograph.', cashSeconds: -180 },
      },
      {
        label: 'Decline politely',
        hint: 'Neutral, safe',
        odds: 1,
        good: { text: 'You stay out of it entirely. Nobody owes anybody anything.', morale: 0.05 },
        bad: { text: '', morale: 0.05 },
      },
    ],
  },
  {
    id: 'any_award',
    category: 'any',
    title: 'You Have Been Nominated',
    body: 'Entrepreneur of the year. The entry fee is substantial, the ceremony is long, and winning it genuinely moves the needle.',
    choices: [
      {
        label: 'Enter and campaign',
        hint: 'Costly, could pay off',
        odds: 0.5,
        good: { text: 'You win. The trophy is ugly and the business it brings is not.', boost: { label: 'Award Winner', kind: 'income', power: 1.6, duration: 900, scope: 'empire' }, luck: 6 },
        bad: { text: 'You lose to a man who sells packaging. The entry fee is not refundable.', cashSeconds: -150 },
      },
      {
        label: 'Ignore it',
        hint: 'Free',
        odds: 1,
        good: { text: 'You delete the email and get on with the day.', cashSeconds: 0 },
        bad: { text: '', cashSeconds: 0 },
      },
    ],
  },
  {
    id: 'any_recession',
    category: 'any',
    title: 'The Economy Is Turning',
    body: 'Every leading indicator has rolled over at once. Nobody knows how deep it goes, and everyone is about to find out together.',
    minLevel: 2,
    choices: [
      {
        label: 'Cut costs early',
        hint: 'Safe, gives up upside',
        odds: 0.85,
        good: { text: 'Lean before the downturn arrives. You trade through it comfortably.', cashSeconds: 180, morale: -0.1 },
        bad: { text: 'The downturn never arrives and you cut into a growing market.', cashSeconds: -160, morale: -0.15 },
      },
      {
        label: 'Buy while everything is cheap',
        hint: 'Aggressive',
        odds: 0.55,
        good: { text: 'You buy assets at prices that will look absurd in two years.', boost: { label: 'Bought The Bottom', kind: 'income', power: 1.8, duration: 1200, scope: 'empire' } },
        bad: { text: 'You caught a falling knife with both hands.', cashSeconds: -420 },
      },
    ],
  },
  {
    id: 'any_succession',
    category: 'any',
    title: 'Who Runs This If You Stop?',
    body: 'Your lawyer has asked, twice, what happens to the group if you are unavailable. There is currently no answer.',
    minLevel: 3,
    choices: [
      {
        label: 'Build a real management layer',
        hint: 'Costly, durable',
        odds: 0.85,
        good: { text: 'A proper executive team. The group runs without you standing in it.', cashSeconds: -220, boost: { label: 'Runs Itself', kind: 'income', power: 1.4, duration: 1500, scope: 'empire' }, morale: 0.2 },
        bad: { text: 'You hire executives who need managing more than the business did.', cashSeconds: -320, morale: -0.15 },
      },
      {
        label: 'Keep everything in your head',
        hint: 'Free, fragile',
        odds: 1,
        good: { text: 'You remain the single point of failure. It is efficient right up until it is not.', cashSeconds: 100 },
        bad: { text: '', cashSeconds: 100 },
      },
    ],
  },
  {
    id: 'any_supplier_collapse',
    category: 'any',
    title: 'A Key Supplier Has Failed',
    body: 'They went into administration overnight. They supplied three of your businesses and there is no obvious replacement.',
    choices: [
      {
        label: 'Buy their assets out of administration',
        hint: 'Opportunistic',
        odds: 0.7,
        good: { text: 'You own your own supply chain now, bought at administration prices.', boost: { label: 'Vertically Integrated', kind: 'income', power: 1.7, duration: 1200, scope: 'empire' } },
        bad: { text: 'You bought equipment you cannot operate and staff who have already left.', cashSeconds: -380 },
      },
      {
        label: 'Find alternatives fast',
        hint: 'Expensive, quick',
        odds: 0.9,
        good: { text: 'Three new suppliers in a fortnight at worse prices, but nothing stopped.', cashSeconds: -150 },
        bad: { text: 'Nobody has capacity at short notice. Two weeks of disruption.', cashSeconds: -260, morale: -0.15 },
      },
    ],
  },
  {
    id: 'any_pr_disaster',
    category: 'any',
    title: 'Something You Said Is Being Quoted',
    body: 'A remark from an old interview is circulating without its context, and the context does not help as much as you would like.',
    choices: [
      {
        label: 'Apologise clearly',
        hint: 'Ends it fastest',
        odds: 0.85,
        good: { text: 'A short, unqualified apology. The cycle ends in two days.', cashSeconds: -90, morale: 0.05 },
        bad: { text: 'The apology is parsed for insincerity and becomes the second story.', cashSeconds: -200, morale: -0.15 },
      },
      {
        label: 'Ride it out',
        hint: 'Free, unpredictable',
        odds: 0.55,
        good: { text: 'You say nothing and it is gone within the week.', cashSeconds: 0 },
        bad: { text: 'Silence extends it. A brand partner distances themselves publicly.', cashSeconds: -280, morale: -0.2 },
      },
    ],
  },
  {
    id: 'any_deal_flow',
    category: 'any',
    title: 'Too Many Opportunities',
    body: 'Four genuinely good deals have landed in the same week and you have the capital for two of them.',
    choices: [
      {
        label: 'Pick the two best',
        hint: 'Disciplined',
        odds: 0.9,
        good: { text: 'Two good deals done properly beats four done badly. Both perform.', cashSeconds: 260, morale: 0.1 },
        bad: { text: 'You picked the wrong two. The other pair did considerably better.', cashSeconds: -80 },
      },
      {
        label: 'Leverage up and take all four',
        hint: 'Greedy',
        odds: 0.45,
        good: { text: 'All four land. An extraordinary quarter built entirely on borrowed money.', cashSeconds: 620, rolls: 2 },
        bad: { text: 'You are overextended when one of them needs more capital.', cashSeconds: -460, morale: -0.2 },
      },
    ],
  },
  {
    id: 'any_ex_employee',
    category: 'any',
    title: 'A Former Employee Is Talking',
    body: 'Someone you let go a year ago is telling a version of events to anyone who will listen, including a journalist.',
    choices: [
      {
        label: 'Settle with them',
        hint: 'Costly, quiet',
        odds: 0.85,
        good: { text: 'A settlement and an agreed statement. It stops immediately.', cashSeconds: -170 },
        bad: { text: 'The settlement itself becomes the story.', cashSeconds: -300, morale: -0.15 },
      },
      {
        label: 'Let them talk',
        hint: 'Free, exposed',
        odds: 0.6,
        good: { text: 'Their account does not survive contact with anyone who was there.', morale: 0.1 },
        bad: { text: 'Two more former employees corroborate it.', cashSeconds: -320, morale: -0.25 },
      },
    ],
  },
];
