import type { EventCardDef } from '../../types';

/** Nightclub deck. Nothing happens until midnight, then everything does. */

export const NIGHTCLUB_CARDS: EventCardDef[] = [
  {
    id: 'club_dj',
    category: 'nightclub',
    title: 'Headline DJ Available',
    body: 'A name act had a festival cancel and has one open Saturday. The booking fee is eye-watering and non-refundable.',
    choices: [
      {
        label: 'Book them',
        hint: 'Expensive, huge night',
        odds: 0.65,
        good: {
          text: 'Sold out in ninety minutes. The queue goes around the block twice.',
          boost: { label: 'Headline Night', kind: 'income', power: 2.6, duration: 300, scope: 'business' },
          morale: 0.2,
          addTag: { tag: 'hot_room', seconds: 900 },
        },
        bad: { text: 'They cancel the morning of. The fee is gone and the room is half empty.', cashSeconds: -300, morale: -0.2 },
      },
      {
        label: 'Push your resident',
        hint: 'Cheap, loyal crowd',
        odds: 0.85,
        good: { text: 'Your resident packs it out anyway. The regulars prefer them.', cashSeconds: 120, morale: 0.15 },
        bad: { text: 'A slow night. The regulars went to see the DJ you passed on.', cashSeconds: -60 },
      },
    ],
  },
  {
    id: 'club_bottle',
    category: 'nightclub',
    title: 'Whale in the VIP Booth',
    body: 'Someone just ordered the entire top shelf and is asking what else you have in the back. Your floor manager wants to know whether to keep pouring.',
    choices: [
      {
        label: 'Keep it coming',
        hint: 'Enormous tab, some risk',
        odds: 0.7,
        good: { text: 'The tab clears five figures and they book the booth for next month.', cashSeconds: 380 },
        bad: { text: 'The card declines at 3am. The tab is a write-off and the booth is destroyed.', cashSeconds: -200, morale: -0.1 },
      },
      {
        label: 'Card on file first',
        hint: 'Safe, slightly smaller',
        odds: 0.95,
        good: { text: 'Pre-authorised and poured. Big tab, zero risk.', cashSeconds: 240 },
        bad: { text: 'They take offence at being asked and leave with their entourage.', cashSeconds: -40 },
      },
    ],
  },
  {
    id: 'club_noise',
    category: 'nightclub',
    title: 'Noise Complaints',
    body: 'The new residential building across the street has filed for the third time this month. The licensing board has taken notice.',
    excludesTag: 'soundproofed',
    choices: [
      {
        label: 'Soundproof the building',
        hint: 'Costly permanent fix',
        odds: 0.9,
        good: { text: 'Acoustic treatment throughout. The complaints stop and the sound is better inside.', cashSeconds: -220, morale: 0.1, addTag: { tag: 'soundproofed', seconds: 2400 } },
        bad: { text: 'The work helps but not enough. Complaints continue at lower volume.', cashSeconds: -260 },
      },
      {
        label: 'Charm the neighbours',
        hint: 'Cheap, unpredictable',
        odds: 0.5,
        good: { text: 'Free guest list and a bottle for the building committee. Complaints evaporate.', cashSeconds: -40 },
        bad: {
          text: 'They were never going to be bought off. Your licence hours are cut.',
          cashSeconds: -180,
          morale: -0.15,
          addTag: { tag: 'licence_risk', seconds: 900 },
          chain: { cardId: 'club_licence_hearing', delay: 200 },
        },
      },
    ],
  },
  {
    id: 'club_licence_hearing',
    category: 'nightclub',
    title: 'Licensing Hearing',
    body: 'The board has scheduled a review of your licence. The residents have organised, hired counsel, and brought a decibel log.',
    chainOnly: true,
    choices: [
      {
        label: 'Bring your own lawyers',
        hint: 'Expensive, effective',
        odds: 0.8,
        good: { text: 'Counsel picks the decibel log apart. Licence retained in full.', cashSeconds: -180, removeTag: 'licence_risk' },
        bad: { text: 'Retained, but with a 1am curfew that guts your best two hours.', cashSeconds: -320, morale: -0.2 },
      },
      {
        label: 'Offer concessions',
        hint: 'Cheap, gives ground',
        odds: 0.9,
        good: { text: 'Earlier close on weeknights buys you the weekend untouched.', cashSeconds: -70, removeTag: 'licence_risk' },
        bad: { text: 'They take the concessions and press for more.', cashSeconds: -200, morale: -0.15 },
      },
    ],
  },
  {
    id: 'club_security',
    category: 'nightclub',
    title: 'Incident at the Door',
    body: 'A fight spilled onto the street at closing. There is phone footage and your head of security wants a decision before the morning.',
    choices: [
      {
        label: 'Get ahead of it',
        hint: 'Costly, protects reputation',
        odds: 0.85,
        good: { text: 'Statement issued, extra security hired, licence intact. Nobody remembers by Friday.', cashSeconds: -120, morale: 0.08 },
        bad: { text: 'The statement reads as an admission. The board schedules a hearing anyway.', cashSeconds: -200, addTag: { tag: 'licence_risk', seconds: 900 } },
      },
      {
        label: 'Say nothing',
        hint: 'Gamble on it dying down',
        odds: 0.55,
        good: { text: 'The footage gets nine views. The news cycle moves on.', cashSeconds: 0 },
        bad: { text: 'It gets picked up. Two weeks of closure while the licence is reviewed.', cashSeconds: -400, morale: -0.25, addTag: { tag: 'licence_risk', seconds: 900 } },
      },
    ],
  },
  {
    id: 'club_brand',
    category: 'nightclub',
    title: 'Spirits Brand Sponsorship',
    body: 'A vodka brand wants exclusive pour rights and a logo on everything. The cheque is large. The vodka is not good.',
    choices: [
      {
        label: 'Take the deal',
        hint: 'Cash now, quality down',
        odds: 0.8,
        good: { text: 'The cheque clears and almost nobody notices the pour changed.', cashSeconds: 260, morale: -0.05 },
        bad: { text: 'Regulars notice immediately. The VIP crowd starts drinking elsewhere.', cashSeconds: 120, morale: -0.25 },
      },
      {
        label: 'Stay independent',
        hint: 'No money, keeps prestige',
        odds: 1,
        good: { text: 'You keep the back bar exactly as it is. The bartenders respect you for it.', morale: 0.15, luck: 1 },
        bad: { text: '', morale: 0.15, luck: 1 },
      },
    ],
  },
  {
    id: 'club_afterhours',
    category: 'nightclub',
    title: 'After-Hours Licence',
    body: 'You could apply to trade until 6am. The application is expensive, the approval uncertain, and the revenue between 4 and 6 is nearly all profit.',
    minLevel: 3,
    excludesTag: 'licence_risk',
    choices: [
      {
        label: 'Apply',
        hint: 'Expensive gamble',
        odds: 0.55,
        good: { text: 'Approved. Two extra hours of the highest-margin trading of the night, permanently.', boost: { label: 'After-Hours Licence', kind: 'income', power: 1.65, duration: 1200, scope: 'business' } },
        bad: { text: 'Denied on residential grounds. The application fee is non-refundable.', cashSeconds: -160 },
      },
      {
        label: 'Not worth the risk',
        hint: 'Skip',
        odds: 1,
        good: { text: 'You close at two like everyone else and sleep marginally better.', morale: 0.05 },
        bad: { text: '', morale: 0.05 },
      },
    ],
  },
  {
    id: 'club_promoter',
    category: 'nightclub',
    title: 'A Promoter Wants Your Wednesdays',
    body: 'They will fill a dead night with their own crowd, keep the door money, and give you the bar. Their crowd is not your crowd.',
    choices: [
      {
        label: 'Give them the night',
        hint: 'Free revenue, borrowed room',
        odds: 0.75,
        good: { text: 'A dead night becomes a bar takings night. You do nothing and get paid.', boost: { label: 'Promoter Night', kind: 'income', power: 1.4, duration: 720, scope: 'business' } },
        bad: { text: 'Their crowd wrecks the place and drinks tap water. Never again.', cashSeconds: -160, morale: -0.15 },
      },
      {
        label: 'Programme it yourself',
        hint: 'Slower, keeps the room',
        odds: 0.6,
        good: { text: 'You build a midweek night that belongs to you. Slow start, real asset.', boost: { label: 'Midweek Residency', kind: 'income', power: 1.5, duration: 1200, scope: 'business' } },
        bad: { text: 'Empty room, paid staff, three months of trying.', cashSeconds: -190 },
      },
    ],
  },
  {
    id: 'club_soundsystem',
    category: 'nightclub',
    title: 'The Sound System Is Tired',
    body: 'The rig is a decade old and the low end has gone soft. DJs have started mentioning it, which means they are mentioning it elsewhere too.',
    minLevel: 2,
    choices: [
      {
        label: 'Install a serious rig',
        hint: 'Enormous cost, real draw',
        odds: 0.85,
        good: {
          text: 'A proper system becomes the reason people choose your room. Bookings get easier.',
          cashSeconds: -260,
          boost: { label: 'World-Class Sound', kind: 'income', power: 1.65, duration: 1500, scope: 'business' },
          addTag: { tag: 'hot_room', seconds: 1200 },
        },
        bad: { text: 'Beautiful rig, badly tuned for the room. Expensive and no better.', cashSeconds: -320 },
      },
      {
        label: 'Repair what you have',
        hint: 'Cheap, temporary',
        odds: 0.8,
        good: { text: 'New drivers and a retune. Good enough for another two years.', cashSeconds: -70 },
        bad: { text: 'The repair reveals the amps are failing too.', cashSeconds: -180 },
      },
    ],
  },
  {
    id: 'club_hot_room',
    category: 'nightclub',
    title: 'Everyone Wants In',
    body: 'The room is the room this season. There is a queue at eleven and agents are calling you now instead of the other way round.',
    requiresTag: 'hot_room',
    choices: [
      {
        label: 'Raise the door and the minimums',
        hint: 'Monetise the moment',
        odds: 0.8,
        good: { text: 'Nobody blinks at the new prices. The moment is worth what you charge for it.', boost: { label: 'Peak Pricing', kind: 'income', power: 1.9, duration: 600, scope: 'business' } },
        bad: { text: 'You priced the crowd that made it hot out of their own room.', cashSeconds: -170, removeTag: 'hot_room', morale: -0.15 },
      },
      {
        label: 'Keep it accessible',
        hint: 'Extends the run',
        odds: 0.85,
        good: { text: 'Same door, same crowd, and the season lasts twice as long.', addTag: { tag: 'hot_room', seconds: 1500 }, boost: { label: 'Long Season', kind: 'income', power: 1.4, duration: 1200, scope: 'business' } },
        bad: { text: 'You left money on the table and the heat faded anyway.', removeTag: 'hot_room', cashSeconds: -40 },
      },
    ],
  },
  {
    id: 'club_drugs',
    category: 'nightclub',
    title: 'Something Is Going On In The Toilets',
    body: 'Your head of security has been clear about what they are finding, and about what happens to your licence if the police find it first.',
    choices: [
      {
        label: 'Hard search policy',
        hint: 'Costs entry, protects licence',
        odds: 0.85,
        good: { text: 'Search on entry, attendants on the door. It costs a slice of the crowd and saves the room.', cashSeconds: -100, removeTag: 'licence_risk' },
        bad: { text: 'The queue doubles, the crowd thins, and the problem relocates rather than stops.', cashSeconds: -170, morale: -0.1 },
      },
      {
        label: 'Handle it quietly',
        hint: 'Cheap, exposed',
        odds: 0.5,
        good: { text: 'Discreet pressure works and nothing reaches the licensing board.', cashSeconds: -30 },
        bad: { text: 'A licensing visit finds exactly what your security warned you about.', cashSeconds: -350, morale: -0.25, addTag: { tag: 'licence_risk', seconds: 1200 } },
      },
    ],
  },
  {
    id: 'club_festival',
    category: 'nightclub',
    title: 'Run a Festival Stage',
    body: 'A festival wants your club to curate and brand a stage. Enormous exposure, enormous logistics, and a fee that only just covers costs.',
    minLevel: 4,
    choices: [
      {
        label: 'Take the stage',
        hint: 'Brand play',
        odds: 0.7,
        good: {
          text: 'Twelve thousand people see your name on a stage. The club is full for months.',
          boost: { label: 'Festival Stage', kind: 'income', power: 1.8, duration: 1200, scope: 'business' },
          addTag: { tag: 'hot_room', seconds: 1200 },
          luck: 4,
        },
        bad: { text: 'Rain, a broken generator, and your name on a stage nobody could hear.', cashSeconds: -280, morale: -0.15 },
      },
      {
        label: 'Stay home',
        hint: 'Focus on the room',
        odds: 1,
        good: { text: 'You run your own room on a busy weekend instead. Reliable money.', cashSeconds: 90 },
        bad: { text: '', cashSeconds: 90 },
      },
    ],
  },
  {
    id: 'club_bar_theft',
    category: 'nightclub',
    title: 'The Pour Costs Do Not Add Up',
    body: 'Stock says one thing, tills say another, and the gap is the price of a small car every month.',
    choices: [
      {
        label: 'Install measured pourers',
        hint: 'Systemic fix',
        odds: 0.85,
        good: { text: 'Every measure logged. The gap closes overnight without anyone being accused.', cashSeconds: -80, morale: -0.05 },
        bad: { text: 'The bartenders work around them within a week.', cashSeconds: -140 },
      },
      {
        label: 'Confront the bar team',
        hint: 'Direct, divisive',
        odds: 0.5,
        good: { text: 'Two resignations and the numbers correct themselves immediately.', staff: -1, cashSeconds: 90 },
        bad: { text: 'You accused the wrong people and the good ones left.', staff: -2, morale: -0.3 },
      },
    ],
  },
  {
    id: 'club_celeb',
    category: 'nightclub',
    title: 'A Famous Person Is In The Building',
    body: 'They came in quietly and want it kept that way. Your door staff have already been offered money for a photograph.',
    choices: [
      {
        label: 'Protect their privacy',
        hint: 'No headlines, real loyalty',
        odds: 0.9,
        good: { text: 'Nothing gets out. They come back, and bring people, for years.', boost: { label: 'Discreet Room', kind: 'income', power: 1.5, duration: 1200, scope: 'business' }, luck: 6 },
        bad: { text: 'Someone talks anyway, and now you look like you cannot control your own room.', cashSeconds: -110, morale: -0.1 },
      },
      {
        label: 'Let the photos happen',
        hint: 'Free publicity, one-time',
        odds: 0.7,
        good: { text: 'The club is in every tabloid by morning. The queue is enormous for a fortnight.', boost: { label: 'Tabloid Bump', kind: 'income', power: 1.9, duration: 300, scope: 'business' } },
        bad: { text: 'Their people make it very clear that nobody in their circle will return.', cashSeconds: -180 },
      },
    ],
  },
  {
    id: 'club_capacity',
    category: 'nightclub',
    title: 'Over Capacity',
    body: 'The clicker says you are eighty people over. There is a queue outside willing to pay and a fire officer who could arrive at any time.',
    choices: [
      {
        label: 'Stop the door now',
        hint: 'Lose money, stay legal',
        odds: 1,
        good: { text: 'You close the door and lose the queue. Everyone inside is legal.', cashSeconds: -60, morale: 0.1 },
        bad: { text: '', cashSeconds: -60, morale: 0.1 },
      },
      {
        label: 'Keep letting them in',
        hint: 'Big night, real exposure',
        odds: 0.6,
        good: { text: 'Best door take of the year and nobody official showed up.', cashSeconds: 300 },
        bad: { text: 'A fire officer walks in at one. Immediate closure and a licence referral.', cashSeconds: -420, morale: -0.25, addTag: { tag: 'licence_risk', seconds: 1200 } },
      },
    ],
  },
  {
    id: 'club_resident',
    category: 'nightclub',
    title: 'Your Resident Is Getting Famous',
    body: 'The DJ who built your Friday is booking festivals now. They still play for you at the old rate, and their agent has noticed.',
    minLevel: 3,
    choices: [
      {
        label: 'Pay them properly',
        hint: 'Costly, keeps the night',
        odds: 0.9,
        good: { text: 'They stay because you did the right thing before you had to.', cashSeconds: -130, morale: 0.3, boost: { label: 'Loyal Resident', kind: 'income', power: 1.4, duration: 1200, scope: 'business' } },
        bad: { text: 'You pay the new rate and they leave three months later anyway.', cashSeconds: -190, morale: -0.1 },
      },
      {
        label: 'Hold them to the contract',
        hint: 'Cheap, finite',
        odds: 0.45,
        good: { text: 'They honour it to the last date, professionally, and never speak to you again.', cashSeconds: 110, morale: -0.15 },
        bad: { text: 'They walk, the Friday collapses, and the scene hears why.', cashSeconds: -240, morale: -0.3 },
      },
    ],
  },
  {
    id: 'club_refurb',
    category: 'nightclub',
    title: 'The Room Looks Its Age',
    body: 'Under the lights it is fine. With the house lights on it is a carpet that has seen things. Closing to refurbish means closing.',
    minLevel: 4,
    choices: [
      {
        label: 'Full refurbishment',
        hint: 'Dark for weeks, reborn after',
        odds: 0.8,
        good: { text: 'Six weeks dark, then a room that feels new. The relaunch is enormous.', cashSeconds: -300, boost: { label: 'Relaunched', kind: 'income', power: 2.0, duration: 1200, scope: 'business' }, addTag: { tag: 'hot_room', seconds: 900 } },
        bad: { text: 'The works overrun by a month and the crowd found somewhere else.', cashSeconds: -420, morale: -0.2 },
      },
      {
        label: 'Refresh in stages',
        hint: 'Stay open, slower',
        odds: 0.9,
        good: { text: 'A section at a time, Mondays only. Nobody notices until it is all done.', cashSeconds: -140, boost: { label: 'Freshened Up', kind: 'income', power: 1.3, duration: 900, scope: 'business' } },
        bad: { text: 'Permanent low-level building work. The room never feels finished.', cashSeconds: -180, morale: -0.1 },
      },
    ],
  },
];
