import type { EventCardDef } from '../../types';

/** Restaurant deck. High ceiling, high drama, everything is personal. */

export const RESTAURANT_CARDS: EventCardDef[] = [
  {
    id: 'rest_critic',
    category: 'restaurant',
    title: 'A Critic Is In The Dining Room',
    body: 'Table nine. No reservation under a real name, photographing every course. Your head chef has noticed and is visibly unravelling.',
    choices: [
      {
        label: 'Send out the tasting menu',
        hint: 'Swing for the fence',
        odds: 0.55,
        good: {
          text: 'Three stars. The phone has not stopped ringing since the review dropped.',
          boost: { label: 'Rave Review', kind: 'income', power: 2.4, duration: 420, scope: 'business' },
          morale: 0.25,
          addTag: { tag: 'acclaimed', seconds: 1200 },
          chain: { cardId: 'rest_fully_booked', delay: 300 },
        },
        bad: {
          text: 'The kitchen buckles under the pressure. "Ambitious and undercooked," they write.',
          cashSeconds: -150,
          morale: -0.28,
          addTag: { tag: 'bad_press', seconds: 900 },
        },
      },
      {
        label: 'Play the hits',
        hint: 'Safe, modest reward',
        odds: 0.85,
        good: {
          text: '"Reliable, warm, unpretentious." Not a rave, but bookings tick up.',
          boost: { label: 'Solid Notice', kind: 'income', power: 1.35, duration: 300, scope: 'business' },
        },
        bad: { text: '"Competent but forgettable." No harm done, no help either.', morale: -0.05 },
      },
    ],
  },
  {
    id: 'rest_fully_booked',
    category: 'restaurant',
    title: 'Booked Solid For Two Months',
    body: 'You cannot seat everyone who wants a table. The waiting list is a business asset and also a source of daily complaints.',
    chainOnly: true,
    choices: [
      {
        label: 'Raise prices',
        hint: 'Fewer guests, better margin',
        odds: 0.8,
        good: { text: 'Demand barely dips. You should have done it a year ago.', boost: { label: 'Priced To Demand', kind: 'income', power: 1.6, duration: 900, scope: 'business' } },
        bad: { text: 'The regulars notice and say so, loudly, in reviews.', cashSeconds: -120, morale: -0.15 },
      },
      {
        label: 'Add a second sitting',
        hint: 'More covers, more strain',
        odds: 0.7,
        good: { text: 'Two sittings a night, same rent. The kitchen holds.', boost: { label: 'Double Sitting', kind: 'income', power: 1.75, duration: 720, scope: 'business' }, morale: -0.08 },
        bad: { text: 'Service quality drops under the pace and the acclaim fades fast.', cashSeconds: -140, morale: -0.2, removeTag: 'acclaimed' },
      },
    ],
  },
  {
    id: 'rest_bad_press_recover',
    category: 'restaurant',
    title: 'Living Down The Review',
    body: 'Bookings are still soft. The bad write-up is the first thing anyone finds when they search you.',
    requiresTag: 'bad_press',
    choices: [
      {
        label: 'Invite them back',
        hint: 'Bold, could reverse it',
        odds: 0.55,
        good: { text: 'They return, and print a correction that is better than the original review.', removeTag: 'bad_press', boost: { label: 'Redemption Notice', kind: 'income', power: 1.7, duration: 600, scope: 'business' } },
        bad: { text: 'They return and confirm their first impression in more detail.', cashSeconds: -170, morale: -0.2 },
      },
      {
        label: 'Wait it out',
        hint: 'Slow, free',
        odds: 0.85,
        good: { text: 'A few quiet months and the internet forgets. It always does.', removeTag: 'bad_press', cashSeconds: -50 },
        bad: { text: 'It stays pinned to the top of every search result.', cashSeconds: -110 },
      },
    ],
  },
  {
    id: 'rest_chef',
    category: 'restaurant',
    title: 'Your Chef Has an Offer',
    body: 'A competitor offered your head chef their own kitchen and 40% more. They came to you first, which means something.',
    choices: [
      {
        label: 'Beat the offer',
        hint: 'Costly, keeps the talent',
        odds: 0.9,
        good: { text: 'They stay, and they are loyal about it. The kitchen settles.', cashSeconds: -140, morale: 0.3 },
        bad: { text: 'They take your counter to the competitor and leverage it higher. Gone anyway.', cashSeconds: -140, morale: -0.25, staff: -1, addTag: { tag: 'no_chef' } },
      },
      {
        label: 'Offer equity instead',
        hint: 'Clever, uncertain',
        odds: 0.6,
        good: {
          text: 'A share of the restaurant means more than salary. They are all in now.',
          boost: { label: 'Chef-Owner', kind: 'income', power: 1.45, duration: 900, scope: 'business' },
          morale: 0.35,
        },
        bad: { text: 'They wanted cash, not paper. They leave and take two line cooks with them.', morale: -0.35, staff: -2, addTag: { tag: 'no_chef' } },
      },
      {
        label: 'Let them go',
        hint: 'Cheap now, hurts later',
        odds: 1,
        good: { text: 'You wish them well and promote the sous chef. Rocky few weeks ahead.', morale: -0.18, staff: -1, cashSeconds: 40, addTag: { tag: 'no_chef' } },
        bad: { text: '', morale: -0.18, staff: -1, cashSeconds: 40 },
      },
    ],
  },
  {
    id: 'rest_new_chef',
    category: 'restaurant',
    title: 'Finding a New Head Chef',
    body: 'The sous chef is holding it together but the menu has not changed in weeks and everyone can taste the drift.',
    requiresTag: 'no_chef',
    choices: [
      {
        label: 'Poach a name',
        hint: 'Expensive, transformative',
        odds: 0.65,
        good: { text: 'A real name takes the kitchen and rewrites everything. The room feels different.', cashSeconds: -200, removeTag: 'no_chef', boost: { label: 'New Kitchen', kind: 'income', power: 1.8, duration: 900, scope: 'business' }, morale: 0.3 },
        bad: { text: 'Enormous ego, enormous salary, three resignations in a fortnight.', cashSeconds: -300, morale: -0.25, staff: -2 },
      },
      {
        label: 'Promote the sous chef',
        hint: 'Cheap, loyal, unproven',
        odds: 0.75,
        good: { text: 'They have been ready for a year. The team is delighted.', removeTag: 'no_chef', morale: 0.35, boost: { label: 'Promoted Within', kind: 'income', power: 1.3, duration: 900, scope: 'business' } },
        bad: { text: 'They are a brilliant cook and a poor manager. The rota descends into chaos.', cashSeconds: -140, morale: -0.15 },
      },
    ],
  },
  {
    id: 'rest_inspection',
    category: 'restaurant',
    title: 'Health Inspector',
    body: 'Unannounced visit. The walk-in has been running two degrees warm all week and you have been meaning to call someone about it.',
    choices: [
      {
        label: 'Full transparency',
        hint: 'Honest, small penalty',
        odds: 0.8,
        good: { text: 'You flag it yourself. They note the repair order and pass you with a warning.', cashSeconds: -50, morale: 0.1 },
        bad: { text: 'Honesty earns you a formal citation anyway. Bureaucracy is bureaucracy.', cashSeconds: -130 },
      },
      {
        label: 'Hope they miss it',
        hint: 'Gamble',
        odds: 0.5,
        good: { text: 'They never open the walk-in. Clean pass, and you fix it that night.', cashSeconds: -15 },
        bad: { text: 'Immediate closure order. Three days dark and a public notice on the door.', cashSeconds: -320, morale: -0.3, addTag: { tag: 'bad_press', seconds: 600 } },
      },
    ],
  },
  {
    id: 'rest_delivery',
    category: 'restaurant',
    title: 'Delivery Apps Come Calling',
    body: 'A delivery platform wants you on their marketplace. They take 28% of every order and own the customer relationship.',
    choices: [
      {
        label: 'Sign up',
        hint: 'Volume at low margin',
        odds: 0.75,
        good: { text: 'Order volume doubles. The margin is ugly but the kitchen is never idle.', boost: { label: 'Delivery Volume', kind: 'income', power: 1.4, duration: 480, scope: 'business' } },
        bad: { text: 'Delivery orders cannibalise your dine-in covers at a third of the margin.', cashSeconds: -100 },
      },
      {
        label: 'Build your own ordering',
        hint: 'Slow burn, keeps margin',
        odds: 0.55,
        good: { text: 'Regulars order direct. You keep every cent and own the data.', boost: { label: 'Direct Orders', kind: 'income', power: 1.6, duration: 900, scope: 'business' } },
        bad: { text: 'Nobody downloads a single-restaurant app. The development bill arrives regardless.', cashSeconds: -180 },
      },
    ],
  },
  {
    id: 'rest_private',
    category: 'restaurant',
    title: 'Private Buyout Request',
    body: 'A wedding party wants the entire dining room on your busiest Saturday of the year. They are offering well above a normal night.',
    choices: [
      {
        label: 'Take the booking',
        hint: 'Guaranteed money',
        odds: 1,
        good: { text: 'One party, one bill, no walk-ins. Easiest money you will make this month.', cashSeconds: 190 },
        bad: { text: '', cashSeconds: 190 },
      },
      {
        label: 'Hold the room',
        hint: 'Bet on regulars',
        odds: 0.5,
        good: { text: 'A packed regular service outperforms the buyout, and the regulars remember.', cashSeconds: 280, morale: 0.12 },
        bad: { text: 'Rain. Half the reservations no-show. You turned down a sure thing.', cashSeconds: -60 },
      },
    ],
  },
  {
    id: 'rest_expand',
    category: 'restaurant',
    title: 'The Space Next Door Is Free',
    body: 'The unit adjoining yours went dark. You could double your covers, or open a bar that feeds the dining room.',
    minLevel: 4,
    choices: [
      {
        label: 'Double the dining room',
        hint: 'Big spend, big capacity',
        odds: 0.7,
        good: { text: 'Covers double and the wait list finally clears. The room hums.', boost: { label: 'Expanded Room', kind: 'income', power: 1.7, duration: 900, scope: 'business' } },
        bad: { text: 'You built for a crowd that never arrived. Empty tables cost more than no tables.', cashSeconds: -280, morale: -0.12 },
      },
      {
        label: 'Open a cocktail bar',
        hint: 'Higher margin, needs a crowd',
        odds: 0.6,
        good: { text: 'Waiting guests drink. Drink margins are obscene. Everybody wins.', boost: { label: 'Bar Program', kind: 'income', power: 1.85, duration: 720, scope: 'business' } },
        bad: { text: 'The licence takes four months and the buildout runs over budget.', cashSeconds: -240 },
      },
    ],
  },
  {
    id: 'rest_noshow',
    category: 'restaurant',
    title: 'No-Show Epidemic',
    body: 'A quarter of Friday\'s bookings simply did not arrive. Empty tables on your best night, and a wait list you turned away.',
    choices: [
      {
        label: 'Take card details on booking',
        hint: 'Deters both ways',
        odds: 0.8,
        good: { text: 'No-shows collapse to almost nothing. A few people grumble and book anyway.', boost: { label: 'Guaranteed Covers', kind: 'income', power: 1.3, duration: 720, scope: 'business' } },
        bad: { text: 'Bookings drop as much as no-shows did. Net nothing, plus admin.', cashSeconds: -70 },
      },
      {
        label: 'Overbook deliberately',
        hint: 'Airline logic',
        odds: 0.6,
        good: { text: 'The maths works. Every table full, every night.', cashSeconds: 130 },
        bad: { text: 'Everyone shows up. You turn away people holding confirmed bookings.', cashSeconds: -110, morale: -0.2, addTag: { tag: 'bad_press', seconds: 480 } },
      },
    ],
  },
  {
    id: 'rest_supplier_fish',
    category: 'restaurant',
    title: 'The Fish Did Not Arrive',
    body: 'Friday service in four hours and the supplier van has broken down two counties away. A third of the menu is unservable.',
    choices: [
      {
        label: 'Rewrite the menu now',
        hint: 'Chaos, then a story',
        odds: 0.7,
        good: { text: 'The kitchen improvises brilliantly. Guests think it was planned.', morale: 0.2, cashSeconds: 40 },
        bad: { text: 'Rushed dishes, long waits, and a dining room that noticed.', cashSeconds: -130, morale: -0.15 },
      },
      {
        label: 'Buy retail at any price',
        hint: 'Expensive, service intact',
        odds: 0.9,
        good: { text: 'You pay supermarket prices for restaurant volume. Service runs perfectly.', cashSeconds: -90 },
        bad: { text: 'Nowhere has the volume you need. You do it anyway and still fall short.', cashSeconds: -150 },
      },
    ],
  },
  {
    id: 'rest_wine',
    category: 'restaurant',
    title: 'Invest in a Cellar',
    body: 'A sommelier proposes a serious wine programme. It ties up capital in bottles that only get more valuable, and doubles the average bill.',
    minLevel: 3,
    choices: [
      {
        label: 'Build the cellar',
        hint: 'Capital in, margin up',
        odds: 0.75,
        good: { text: 'The list becomes a reason to come. Wine margin carries the whole room.', boost: { label: 'Wine Programme', kind: 'income', power: 1.55, duration: 1200, scope: 'business' } },
        bad: { text: 'Beautiful list, wrong clientele. The capital sits in a basement.', cashSeconds: -220 },
      },
      {
        label: 'Keep it simple',
        hint: 'No capital tied up',
        odds: 1,
        good: { text: 'Six by the glass, all of them good. Nobody has ever complained.', cashSeconds: 30 },
        bad: { text: '', cashSeconds: 30 },
      },
    ],
  },
  {
    id: 'rest_allergy',
    category: 'restaurant',
    title: 'An Allergy Incident',
    body: 'A guest reacted badly to a dish. They are fine. The paperwork, the family, and the question of whose mistake it was are not fine.',
    choices: [
      {
        label: 'Take full responsibility',
        hint: 'Costly, correct',
        odds: 0.85,
        good: { text: 'You apologise properly, retrain everyone, and publish the allergen matrix. Respect earned.', cashSeconds: -130, morale: 0.15, luck: 3 },
        bad: { text: 'The admission is used against you in the claim that follows.', cashSeconds: -280 },
      },
      {
        label: 'Refer it to insurers',
        hint: 'Cold, safe',
        odds: 0.75,
        good: { text: 'Handled at arm\'s length. Settled quietly, no admission.', cashSeconds: -90 },
        bad: { text: 'The family goes public about being handled at arm\'s length.', cashSeconds: -190, morale: -0.2, addTag: { tag: 'bad_press', seconds: 600 } },
      },
    ],
  },
  {
    id: 'rest_michelin',
    category: 'restaurant',
    title: 'The Guide Is Watching',
    body: 'Word is you are on the list for a star this year. Getting one changes everything. Chasing one has ended better restaurants than yours.',
    minLevel: 5,
    requiresTag: 'acclaimed',
    choices: [
      {
        label: 'Chase it',
        hint: 'All in',
        odds: 0.5,
        good: {
          text: 'The star lands. You are booked out for a year and the phone will not stop.',
          boost: { label: 'Starred', kind: 'income', power: 2.6, duration: 1500, scope: 'business' },
          morale: 0.4,
          luck: 8,
        },
        bad: { text: 'You spent a fortune chasing a standard nobody asked for and missed anyway.', cashSeconds: -380, morale: -0.3 },
      },
      {
        label: 'Keep doing what works',
        hint: 'Steady',
        odds: 0.9,
        good: { text: 'No star, no debt, a full room every night. Plenty of people would take that.', boost: { label: 'Quietly Excellent', kind: 'income', power: 1.35, duration: 1200, scope: 'business' }, morale: 0.15 },
        bad: { text: 'Standing still is a choice, and the acclaim cools.', removeTag: 'acclaimed', cashSeconds: -60 },
      },
    ],
  },
  {
    id: 'rest_influencer_meal',
    category: 'restaurant',
    title: 'A Table Wants a Free Meal',
    body: 'Four people, no booking, a lot of ring lights, and a follower count they have mentioned three times.',
    choices: [
      {
        label: 'Comp the table',
        hint: 'Gamble on reach',
        odds: 0.55,
        good: { text: 'The post does numbers and the bookings follow.', boost: { label: 'Feed Famous', kind: 'income', power: 1.7, duration: 360, scope: 'business' } },
        bad: { text: 'They eat, film nothing usable, and leave no tip.', cashSeconds: -80, morale: -0.1 },
      },
      {
        label: 'Give them the bill',
        hint: 'Principled',
        odds: 0.85,
        good: { text: 'They pay. The staff quietly enjoy it. Nothing bad happens.', cashSeconds: 40, morale: 0.15 },
        bad: { text: 'A snide story to a hundred thousand people. It blows over in a day.', cashSeconds: -50 },
      },
    ],
  },
  {
    id: 'rest_lunch',
    category: 'restaurant',
    title: 'Open For Lunch?',
    body: 'The room sits empty until six. Lunch service means more staff hours for a thinner crowd, but the rent is already paid.',
    minLevel: 2,
    choices: [
      {
        label: 'Open for lunch',
        hint: 'More hours, thinner margin',
        odds: 0.65,
        good: { text: 'The office crowd finds you. Lunch becomes a third of the week\'s revenue.', boost: { label: 'Lunch Trade', kind: 'income', power: 1.45, duration: 1200, scope: 'business' } },
        bad: { text: 'Six covers a day and an exhausted kitchen. You stop after a month.', cashSeconds: -140, morale: -0.15 },
      },
      {
        label: 'Dinner only',
        hint: 'Focus',
        odds: 1,
        good: { text: 'One service, done properly, by people who slept.', morale: 0.1 },
        bad: { text: '', morale: 0.1 },
      },
    ],
  },
  {
    id: 'rest_staff_meal',
    category: 'restaurant',
    title: 'The Team Is Burning Out',
    body: 'Doubles, split shifts, and a rota that has not had a gap in it since spring. Two people have called in sick on the same Friday.',
    choices: [
      {
        label: 'Close one day a week',
        hint: 'Lose revenue, keep people',
        odds: 0.9,
        good: { text: 'A guaranteed day off transforms the place. Turnover stops dead.', cashSeconds: -100, morale: 0.4 },
        bad: { text: 'The lost day costs more than you expected and the exhaustion persists.', cashSeconds: -170, morale: 0.1 },
      },
      {
        label: 'Hire more cover',
        hint: 'Costly, keeps the days',
        odds: 0.8,
        good: { text: 'Extra hands ease the rota without losing a service.', cashSeconds: -80, staff: 1, morale: 0.2 },
        bad: { text: 'Good cover staff are not available at short notice in this market.', cashSeconds: -120, morale: -0.1 },
      },
    ],
  },
  {
    id: 'rest_second_site',
    category: 'restaurant',
    title: 'A Second Site',
    body: 'An investor will fund a second restaurant if you run it. Everything you built here would have to work without you standing in it.',
    minLevel: 5,
    choices: [
      {
        label: 'Take the funding',
        hint: 'Growth, divided attention',
        odds: 0.6,
        good: { text: 'The systems hold. Two rooms, one standard, someone else\'s capital.', boost: { label: 'Second Site', kind: 'income', power: 1.9, duration: 1200, scope: 'business' } },
        bad: { text: 'Both restaurants get half of you, and it shows in both.', cashSeconds: -260, morale: -0.25 },
      },
      {
        label: 'Stay one restaurant',
        hint: 'Depth over width',
        odds: 1,
        good: { text: 'One room, run properly, for as long as you want to run it.', morale: 0.2, boost: { label: 'Undivided', kind: 'income', power: 1.2, duration: 900, scope: 'business' } },
        bad: { text: '', morale: 0.2 },
      },
    ],
  },
];
