import type { EventCardDef } from '../../types';

/** Tech deck. Burn cash, chase a curve, ship through the fire. */

export const TECH_CARDS: EventCardDef[] = [
  {
    id: 'tech_funding',
    category: 'tech',
    title: 'Term Sheet on the Table',
    body: 'A fund wants in at a valuation that flatters everyone. The terms include a liquidation preference you had to read three times.',
    excludesTag: 'funded',
    choices: [
      {
        label: 'Sign it',
        hint: 'Capital now, strings attached',
        odds: 0.75,
        good: {
          text: 'Money in the bank. You hire aggressively and ship twice as fast.',
          boost: { label: 'Series A', kind: 'income', power: 1.9, duration: 600, scope: 'business' },
          staff: 2,
          addTag: { tag: 'funded', seconds: 1500 },
          chain: { cardId: 'tech_board_meeting', delay: 320 },
        },
        bad: { text: 'The preference triggers on a down round. You work for the fund now.', cashSeconds: -260, morale: -0.2 },
      },
      {
        label: 'Bootstrap',
        hint: 'Slower, keeps control',
        odds: 0.6,
        good: { text: 'Profitable and independent. Growth is slower and entirely yours.', boost: { label: 'Default Alive', kind: 'income', power: 1.35, duration: 1200, scope: 'business' }, morale: 0.2 },
        bad: { text: 'A funded competitor outspends you on every channel. Growth stalls.', cashSeconds: -180 },
      },
    ],
  },
  {
    id: 'tech_board_meeting',
    category: 'tech',
    title: 'Your First Board Meeting',
    body: 'The deck says growth. The board wants to know why growth is not more growth, and has opinions about your burn rate.',
    chainOnly: true,
    choices: [
      {
        label: 'Commit to aggressive targets',
        hint: 'Buys goodwill, sets a trap',
        odds: 0.55,
        good: { text: 'You hit the number. The board becomes an asset instead of an audience.', boost: { label: 'Board Confidence', kind: 'income', power: 1.8, duration: 900, scope: 'business' } },
        bad: { text: 'You miss by a third and spend two quarters explaining it.', cashSeconds: -220, morale: -0.25 },
      },
      {
        label: 'Push back with the real numbers',
        hint: 'Uncomfortable, honest',
        odds: 0.8,
        good: { text: 'They respect the candour and extend the runway without drama.', cashSeconds: 90, morale: 0.2 },
        bad: { text: 'Candour reads as a lack of ambition. They start looking for a new CEO.', cashSeconds: -140, morale: -0.2 },
      },
    ],
  },
  {
    id: 'tech_outage',
    category: 'tech',
    title: 'Production Is Down',
    body: 'Everything is on fire. The status page is red, the largest customer is on the phone, and the on-call engineer just said the word "irrecoverable".',
    choices: [
      {
        label: 'All hands, all night',
        hint: 'Burnout risk, fast recovery',
        odds: 0.85,
        good: { text: 'Restored in six hours. The postmortem is excellent and the customer stays.', cashSeconds: -80, morale: -0.12 },
        bad: { text: 'Eighteen hours down. Two engineers quit the following week.', cashSeconds: -300, morale: -0.3, staff: -2, addTag: { tag: 'tech_debt', seconds: 900 } },
      },
      {
        label: 'Restore from backup',
        hint: 'Loses data, restores fast',
        odds: 0.7,
        good: { text: 'Back up in ninety minutes. Four hours of data gone and nobody complains loudly.', cashSeconds: -120 },
        bad: { text: 'The backup was untested. It restores into the same broken state.', cashSeconds: -380, morale: -0.2, addTag: { tag: 'tech_debt', seconds: 900 } },
      },
    ],
  },
  {
    id: 'tech_debt_payoff',
    category: 'tech',
    title: 'The Codebase Is Fighting Back',
    body: 'Every change breaks two things. Velocity has halved and the engineers have started using the word "rewrite" in meetings.',
    requiresTag: 'tech_debt',
    choices: [
      {
        label: 'Stop features, pay it down',
        hint: 'Costly quarter, fast after',
        odds: 0.85,
        good: { text: 'A quarter of unglamorous work and the team is twice as fast forever after.', cashSeconds: -180, removeTag: 'tech_debt', boost: { label: 'Clean Codebase', kind: 'income', power: 1.6, duration: 1200, scope: 'business' } },
        bad: { text: 'The cleanup uncovers worse problems underneath.', cashSeconds: -280, morale: -0.15 },
      },
      {
        label: 'Full rewrite',
        hint: 'The classic mistake',
        odds: 0.35,
        good: { text: 'Against all precedent, it works. The new system is genuinely better.', cashSeconds: -300, removeTag: 'tech_debt', boost: { label: 'Version Two', kind: 'income', power: 2.2, duration: 1200, scope: 'business' } },
        bad: { text: 'Eighteen months, two systems to maintain, and no new features.', cashSeconds: -450, morale: -0.3 },
      },
      {
        label: 'Ship features anyway',
        hint: 'Free, compounding',
        odds: 1,
        good: { text: 'You keep shipping on top of it. It works, for now.', cashSeconds: 70, addTag: { tag: 'tech_debt', seconds: 1200 } },
        bad: { text: '', cashSeconds: 70 },
      },
    ],
  },
  {
    id: 'tech_acquihire',
    category: 'tech',
    title: 'Acquisition Interest',
    body: 'A larger company wants to buy the team. It is a good offer for a product they intend to shut down.',
    choices: [
      {
        label: 'Take the exit',
        hint: 'Big one-off payment',
        odds: 1,
        good: { text: 'The deal closes. Your team is absorbed, the product sunsets, the money is real.', cashSeconds: 600, morale: -0.2, staff: -2 },
        bad: { text: '', cashSeconds: 600, morale: -0.2, staff: -2 },
      },
      {
        label: 'Turn it down',
        hint: 'Bet on yourself',
        odds: 0.5,
        good: { text: 'Six months later you are worth four times the offer. The team is electric.', boost: { label: 'Proved Them Wrong', kind: 'income', power: 2.2, duration: 900, scope: 'business' }, morale: 0.3, luck: 2 },
        bad: { text: 'The market turns. The offer is never repeated and morale never recovers.', cashSeconds: -200, morale: -0.3 },
      },
    ],
  },
  {
    id: 'tech_pivot',
    category: 'tech',
    title: 'The Data Says Pivot',
    body: 'One tiny feature accounts for 80% of engagement. The rest of the product is dead weight and everyone can see it.',
    choices: [
      {
        label: 'Bet everything on it',
        hint: 'Wholesale rewrite',
        odds: 0.6,
        good: { text: 'You strip the product to its one good idea. Retention triples overnight.', boost: { label: 'Product-Market Fit', kind: 'income', power: 2.5, duration: 720, scope: 'business' }, morale: 0.25, addTag: { tag: 'pmf', seconds: 1500 } },
        bad: { text: 'You killed the features paying customers were quietly relying on. Churn spikes.', cashSeconds: -320, morale: -0.25 },
      },
      {
        label: 'Ship it as a mode',
        hint: 'Hedged, slower',
        odds: 0.8,
        good: { text: 'You keep both audiences. Growth is real if unspectacular.', boost: { label: 'Careful Growth', kind: 'income', power: 1.4, duration: 600, scope: 'business' } },
        bad: { text: 'Two half-products, one confused roadmap. Engineering velocity halves.', cashSeconds: -140, morale: -0.1, addTag: { tag: 'tech_debt', seconds: 600 } },
      },
    ],
  },
  {
    id: 'tech_scale',
    category: 'tech',
    title: 'Growth Is Breaking Everything',
    body: 'The thing you wanted is happening and the infrastructure was not built for it. Sign-ups are queueing.',
    requiresTag: 'pmf',
    choices: [
      {
        label: 'Throw money at capacity',
        hint: 'Instant, expensive',
        odds: 0.9,
        good: { text: 'The bill triples and every user gets in. Worth it.', cashSeconds: -160, boost: { label: 'Scaled Up', kind: 'income', power: 1.9, duration: 900, scope: 'business' } },
        bad: { text: 'You scaled the wrong layer. Same queue, larger invoice.', cashSeconds: -260 },
      },
      {
        label: 'Rebuild the bottleneck',
        hint: 'Slower, permanent',
        odds: 0.7,
        good: { text: 'Two weeks of focused work removes the ceiling entirely.', boost: { label: 'Built To Scale', kind: 'income', power: 2.1, duration: 1200, scope: 'business' } },
        bad: { text: 'The rebuild takes a month and you lose the wave.', cashSeconds: -240, removeTag: 'pmf', morale: -0.2 },
      },
    ],
  },
  {
    id: 'tech_breach',
    category: 'tech',
    title: 'Security Disclosure',
    body: 'A researcher emailed a working exploit and a 90-day disclosure deadline. Nothing has leaked. Yet.',
    choices: [
      {
        label: 'Patch and pay the bounty',
        hint: 'Costs money, ends the problem',
        odds: 0.95,
        good: { text: 'Patched in four days. The researcher writes a flattering post about your response.', cashSeconds: -90, luck: 1 },
        bad: { text: 'The patch is incomplete. A second researcher finds the same hole.', cashSeconds: -180 },
      },
      {
        label: 'Ignore the email',
        hint: 'Free, reckless',
        odds: 0.35,
        good: { text: 'They lose interest. You get away with it entirely.', cashSeconds: 0 },
        bad: { text: 'Full public disclosure on day 91. Enterprise customers leave in a block.', cashSeconds: -520, morale: -0.3 },
      },
    ],
  },
  {
    id: 'tech_hire',
    category: 'tech',
    title: 'A Famous Engineer Is Available',
    body: 'Someone whose name carries weight is between jobs. They would cost more than the rest of the team combined.',
    minLevel: 3,
    choices: [
      {
        label: 'Pay whatever it takes',
        hint: 'Enormous salary',
        odds: 0.7,
        good: { text: 'They rewrite the core in three weeks and mentor everyone around them.', boost: { label: 'Ten-X Hire', kind: 'income', power: 1.8, duration: 900, scope: 'business' }, staff: 1, morale: 0.2 },
        bad: { text: 'Brilliant and impossible. Three people quit rather than work with them.', cashSeconds: -280, morale: -0.3, staff: -2 },
      },
      {
        label: 'Hire three juniors instead',
        hint: 'Same cost, slower',
        odds: 0.85,
        good: { text: 'They grow into the role. Steady, cheap, loyal capacity.', staff: 3, morale: 0.1, cashSeconds: -60 },
        bad: { text: 'Nobody has time to mentor them. They flounder for a quarter.', cashSeconds: -100, morale: -0.08 },
      },
    ],
  },
  {
    id: 'tech_open_source',
    category: 'tech',
    title: 'Open Source The Core?',
    body: 'Your engineers want to release the engine publicly. It would cost you a moat and buy you a community.',
    minLevel: 3,
    choices: [
      {
        label: 'Open it',
        hint: 'Long game',
        odds: 0.65,
        good: { text: 'Contributors arrive, hiring gets easier, and the standard becomes yours.', boost: { label: 'Community Effect', kind: 'income', power: 1.7, duration: 1500, scope: 'business' }, luck: 5, morale: 0.25 },
        bad: { text: 'A competitor forks it, ships faster, and thanks you in the release notes.', cashSeconds: -240 },
      },
      {
        label: 'Keep it closed',
        hint: 'Defend the moat',
        odds: 1,
        good: { text: 'The engine stays yours. So does every problem in it.', cashSeconds: 50 },
        bad: { text: '', cashSeconds: 50 },
      },
    ],
  },
  {
    id: 'tech_enterprise',
    category: 'tech',
    title: 'An Enterprise Deal',
    body: 'A very large company will sign, provided you build six features, pass a security review, and accept a nine-month sales cycle.',
    minLevel: 2,
    choices: [
      {
        label: 'Chase the whale',
        hint: 'Slow, transformative',
        odds: 0.6,
        good: { text: 'The contract lands and it is worth more than every other customer combined.', boost: { label: 'Enterprise Contract', kind: 'income', power: 2.3, duration: 1200, scope: 'business' } },
        bad: { text: 'Nine months of roadmap spent on a deal that died in procurement.', cashSeconds: -340, morale: -0.25, addTag: { tag: 'tech_debt', seconds: 600 } },
      },
      {
        label: 'Stay self-serve',
        hint: 'Small deals, no drama',
        odds: 0.9,
        good: { text: 'A thousand small customers, none of whom can ruin your quarter.', boost: { label: 'Self-Serve', kind: 'income', power: 1.35, duration: 1200, scope: 'business' } },
        bad: { text: 'Growth flattens without a marquee logo to point at.', cashSeconds: -80 },
      },
    ],
  },
  {
    id: 'tech_ai',
    category: 'tech',
    title: 'Everyone Wants You To Add AI',
    body: 'The board, the customers, and two competitors have all used the phrase this month. Nobody has said what it should do.',
    choices: [
      {
        label: 'Ship something real',
        hint: 'Slow, defensible',
        odds: 0.65,
        good: { text: 'One genuinely useful feature instead of a chatbot. Retention climbs.', boost: { label: 'Actually Useful', kind: 'income', power: 1.75, duration: 1200, scope: 'business' } },
        bad: { text: 'The inference bill exceeds the revenue it generates.', cashSeconds: -230 },
      },
      {
        label: 'Ship the announcement',
        hint: 'Fast, hollow',
        odds: 0.7,
        good: { text: 'The press release does its job. Nobody checks whether it shipped.', cashSeconds: 140, boost: { label: 'Narrative', kind: 'income', power: 1.3, duration: 360, scope: 'business' } },
        bad: { text: 'A journalist checks whether it shipped.', cashSeconds: -160, morale: -0.15 },
      },
    ],
  },
  {
    id: 'tech_cofounder',
    category: 'tech',
    title: 'Your Co-Founder Wants Out',
    body: 'They are tired, they are not enjoying it, and they hold a third of the company. They would like to discuss what happens next.',
    minLevel: 2,
    choices: [
      {
        label: 'Buy them out',
        hint: 'Expensive, clean',
        odds: 0.85,
        good: { text: 'A fair price and a clean cap table. Everyone sleeps better.', cashSeconds: -300, morale: 0.15 },
        bad: { text: 'The valuation dispute takes four months and two law firms.', cashSeconds: -450, morale: -0.2 },
      },
      {
        label: 'Let them keep the equity',
        hint: 'Free now, awkward later',
        odds: 0.6,
        good: { text: 'They step back gracefully and stay a supportive shareholder.', morale: 0.1 },
        bad: { text: 'An absent third owner with strong opinions at every vote.', cashSeconds: -160, morale: -0.2 },
      },
    ],
  },
  {
    id: 'tech_patent',
    category: 'tech',
    title: 'A Patent Letter',
    body: 'A company that makes nothing claims you infringe a patent they bought at auction. They would like to license it to you.',
    choices: [
      {
        label: 'Settle and license',
        hint: 'Certain cost, over with',
        odds: 1,
        good: { text: 'You pay, you license, you never hear from them again.', cashSeconds: -180 },
        bad: { text: '', cashSeconds: -180 },
      },
      {
        label: 'Fight it',
        hint: 'Expensive, principled',
        odds: 0.6,
        good: { text: 'The patent is invalidated. Every company in your sector quietly thanks you.', cashSeconds: -120, luck: 6 },
        bad: { text: 'Two years of legal fees and a judgment against you.', cashSeconds: -420, morale: -0.15 },
      },
    ],
  },
  {
    id: 'tech_remote',
    category: 'tech',
    title: 'Return To The Office?',
    body: 'Half the team moved cities during the remote years. The board thinks the office is underused. The engineers think the office is irrelevant.',
    minLevel: 2,
    choices: [
      {
        label: 'Stay fully remote',
        hint: 'Keeps the team, loses the room',
        odds: 0.85,
        good: { text: 'Nobody leaves, hiring gets easier, and you drop an expensive lease.', cashSeconds: 120, morale: 0.25 },
        bad: { text: 'Onboarding new engineers takes twice as long and culture thins out.', cashSeconds: -110, morale: -0.1 },
      },
      {
        label: 'Mandate three days in',
        hint: 'Loses people, gains focus',
        odds: 0.5,
        good: { text: 'The in-person days genuinely help. A few leave, the rest ship faster.', staff: -1, boost: { label: 'In The Room', kind: 'income', power: 1.4, duration: 900, scope: 'business' } },
        bad: { text: 'Your four best engineers resign in the same fortnight.', staff: -3, morale: -0.35, cashSeconds: -180 },
      },
    ],
  },
  {
    id: 'tech_viral_launch',
    category: 'tech',
    title: 'You Are Top Of The Front Page',
    body: 'Someone posted your product and it took off. Traffic is forty times normal and the servers are making a noise.',
    choices: [
      {
        label: 'Ride it hard',
        hint: 'Capture everything',
        odds: 0.7,
        good: { text: 'You capture the wave. Sign-ups in a day exceed the previous quarter.', boost: { label: 'Front Page', kind: 'income', power: 2.4, duration: 420, scope: 'business' }, addTag: { tag: 'pmf', seconds: 900 } },
        bad: { text: 'You fall over in the first hour and the thread becomes about that.', cashSeconds: -200, morale: -0.2, addTag: { tag: 'tech_debt', seconds: 600 } },
      },
      {
        label: 'Throttle and stay up',
        hint: 'Smaller, reliable',
        odds: 0.95,
        good: { text: 'A waitlist, a stable service, and a good impression on everyone who got in.', boost: { label: 'Controlled Launch', kind: 'income', power: 1.5, duration: 600, scope: 'business' } },
        bad: { text: 'The waitlist reads as vapourware and the moment passes.', cashSeconds: -70 },
      },
    ],
  },
  {
    id: 'tech_pricing',
    category: 'tech',
    title: 'You Are Charging Too Little',
    body: 'A consultant says your price is a third of what the market bears. Your customers have never once complained about the price, which is itself the evidence.',
    minLevel: 3,
    choices: [
      {
        label: 'Triple the price',
        hint: 'Bold',
        odds: 0.6,
        good: { text: 'You lose a tenth of customers and triple revenue. It was never about the price.', boost: { label: 'Repriced', kind: 'income', power: 2.2, duration: 1200, scope: 'business' } },
        bad: { text: 'Churn spikes and the reputation for being good value goes with it.', cashSeconds: -260, morale: -0.15 },
      },
      {
        label: 'Grandfather existing customers',
        hint: 'Slower, keeps goodwill',
        odds: 0.9,
        good: { text: 'New customers pay the new price, old ones stay loyal. Nobody is angry.', boost: { label: 'Grandfathered', kind: 'income', power: 1.5, duration: 1500, scope: 'business' }, morale: 0.1 },
        bad: { text: 'Most of your revenue is grandfathered, so most of it does not move.', cashSeconds: -60 },
      },
    ],
  },
  {
    id: 'tech_burn',
    category: 'tech',
    title: 'Six Months Of Runway',
    body: 'The finance sheet is unambiguous. Cut now while it is a choice, or raise into a market that is not currently interested.',
    requiresTag: 'funded',
    choices: [
      {
        label: 'Cut deep, cut once',
        hint: 'Brutal, survivable',
        odds: 0.85,
        good: { text: 'A hard week and eighteen months of runway. The remaining team knows where they stand.', staff: -2, cashSeconds: 220, morale: -0.2 },
        bad: { text: 'You cut the wrong roles and have to rehire two of them at a premium.', cashSeconds: -140, staff: -2, morale: -0.3 },
      },
      {
        label: 'Raise a bridge',
        hint: 'Keeps the team, costs the cap table',
        odds: 0.6,
        good: { text: 'The existing investors bridge you. Dilution, but nobody loses a job.', cashSeconds: 180, morale: 0.15 },
        bad: { text: 'Nobody bridges. You cut anyway, two months later, from a worse position.', cashSeconds: -280, staff: -3, morale: -0.35 },
      },
    ],
  },
];
