/**
 * Generates dist/sw.js after a Vite build.
 *
 * Written by hand rather than pulled from a plugin: the app is a single static
 * bundle with no runtime fetches, so precaching the build output and serving it
 * cache-first is the whole requirement. The asset list is read from dist/ so
 * Vite's content hashes are always correct.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const DIST = new URL('../dist/', import.meta.url).pathname;

async function walk(dir, base = '') {
  const out = [];
  for (const entry of await readdir(join(DIST, dir), { withFileTypes: true })) {
    const rel = base ? `${base}/${entry.name}` : entry.name;
    if (entry.isDirectory()) out.push(...(await walk(join(dir, entry.name), rel)));
    else out.push(rel);
  }
  return out;
}

const files = (await walk('.')).filter((f) => f !== 'sw.js');

// The cache name embeds a hash of the precache list, so any change to the build
// produces a new cache and the old one is discarded on activate.
const manifest = JSON.stringify(files.sort());
let hash = 0;
for (let i = 0; i < manifest.length; i++) hash = (Math.imul(31, hash) + manifest.charCodeAt(i)) | 0;
const version = (hash >>> 0).toString(36);

const sw = `// Generated by scripts/build-sw.mjs — do not edit.
const CACHE = 'bigbossmoney-${version}';
const PRECACHE = ${JSON.stringify(files.map((f) => './' + f), null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  // Navigations fall back to the cached shell so a cold offline load works.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request).catch(() => caches.match('./index.html').then((r) => r || Response.error())),
    );
    return;
  }

  // Match on the URL rather than the Request. Vite emits its script and style
  // tags with a crossorigin attribute, which makes those requests CORS-mode and
  // stops them matching the precached entries by Request identity.
  event.respondWith(
    caches.match(request.url, { ignoreVary: true }).then((cached) => {
      if (cached) return cached;
      return fetch(request)
        .then((response) => {
          if (response.ok && new URL(request.url).origin === self.location.origin) {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request.url, copy)).catch(() => {});
          }
          return response;
        })
        // A rejected subresource fetch surfaces as ERR_FAILED and breaks the
        // page, so always resolve to something.
        .catch(() => new Response('', { status: 504, statusText: 'Offline' }));
    }),
  );
});
`;

await writeFile(join(DIST, 'sw.js'), sw);
console.log(`sw.js written — ${files.length} files precached, cache bigbossmoney-${version}`);
